NREL/ssc

build_vc2013/solarpilot_vc2013.vcxproj, lpsolve/lp_lib.h, nlopt/sobolseq.c, solarpilot/AutoPilot_API.cpp, solarpilot/AutoPilot_API.h, solarpilot/sort_method.h, tcs/csp_dispatch.cpp, tcs/csp_solver_core.cpp, tcs/csp_solver_gen_collector_receiver.cpp, tcs/csp_solver_lf_dsg_collector_receiver.cpp, tcs/csp_solver_mspt_receiver_222.cpp, tcs/csp_solver_pc_Rankine_indirect_224.cpp, tcs/csp_solver_pc_heat_sink.cpp, tcs/csp_solver_pc_sco2.cpp, tcs/csp_solver_trough_collector_receiver.cpp, tcs/tcskernel.cpp, tcs/tou_translator_csp_solver.cpp
This cleans up all compiler warnings in SSC when building on win32 and x64. I tested the MSPT model and get the same results for the default case.
=> cleaning up remaining csp, solarpilot, and tcs warnings

solarpilot/Heliostat.cpp
Fixes #35. 
* solarpilot/Heliostat.cpp (getPanelById): matrix_t::operator[] only
takes a single int and returns the address of the row. Instead, use
the public at() method to properly access matrix elements by row
and column number.
=> Fix a bug flagged by the warning: left operand of comma operator has no effect

tcs/direct_steam_receivers.cpp
Another potentially nasty bug. Use matrix_t at() method for element accesses. Fixes warning: left operand of comma operator has no effect [-Wunused-value].
This is the first in a series of patches to fix warnings in the tcs directory.
=> Fixes warning: left  operand of comma operator has no effect [-Wunused-value].

solarpilot/Ambient.cpp, solarpilot/Ambient.h, solarpilot/AutoPilot_API.cpp, solarpilot/IOUtil.cpp, solarpilot/LayoutSimulateThread.cpp, solarpilot/SolarField.cpp, solarpilot/definitions.cpp
* Fixes sun position calculation during performance simulations to use instantaneous time rather than time averaged over upcoming hour. This bug primarily affects flux maps, and has no effect on the default SAM case annual performance.
* Fix for heliostat and receiver templates on file loading and during optimization
* Modifies copy constructor on var_map to handle multiple templates. It was previously ignoring all but the base template. Only affect solarpilot standalone and scripting cases with multiple templates using optimization.
=> Several bug fixes to solarpilot

shared/lib_weatherfile.cpp
It looks like at some point the `my_isnan` macro was defined to better support MS Visual Studio toolchains, but was never actually integrated into the `isnan` call later in the code. Then, it looks like that same code was modified to support builds on Linux in 36cb9cc3d43e85ff456e913c973db49f2a04baee.
This PR simply replaces that call with the macro instead so as to include support for both MSVSC and Linux.
=> Using `my_isnan` macro for cross-platform support

solarpilot/Toolbox.cpp
* solarpilot/Toolbox.cpp (Toolbox::getDelimiter): Do not use strcmp. If we want to use the C++ standard library, then we should stop trying to escape to C. :-)
=> Fix compilation error on Linux (strcmp was not declared).

build_linux/Makefile-sdktool, sdktool/dataview.cpp
This couple of very straightforward changes clears all warnings in the sdktools directory.
=> sdktool fixes

solarpilot/AutoPilot_API.h
It is unsafe to delete an instance of a derived class through a pointer to a base class if the base class does not have a virtual destructor. This patch fixes the AutoPilot declaration and silences the warning,
=> Fix warning: deleting object  of polymorphic class type ‘AutoPilot_S’ which has non-virtual  destructor might cause undefined behaviour

shared/lib_irradproc.cpp
=> * lib_irradproc.cpp: Fix warning: ‘poaBest[2]’ may be used uninitialized in this function

tcs/sco2_pc_core.h
A misplaced comma in `sco2_pc_core.h` is prevening `m_phi_rc_1` from being initialised to `quiet_NaN`.
Fixes:
‘s_temp.C_RecompCycle::S_od_turbo_bal_csp_solved::m_phi_rc_1’  is used uninitialized in this function [-Wuninitialized]
=>  Fix warning: m_phi_rc_1 is uninitialized

tcs/csp_solver_two_tank_tes.cpp
Fixes warning: left operand of comma operator has no effect. Issue #67.
=> Properly calculate cp_T_avg.

ssc/cmod_sp_ty.cpp, tcs/csp_solver_gen_collector_receiver.cpp, tcs/csp_solver_lf_dsg_collector_receiver.cpp, tcs/sam_mw_gen_Type260.cpp, tcs/sam_mw_lf_type261_steam.cpp, tcs/sam_mw_lf_type262_salt.cpp
`delete [] a, b, c;` only deletes `a`. The comma operator applies to b and c, so those operands on the right-hand side of the commas are unused values.
=> Fix memory leaks

tcs/sam_mw_type234.cpp
Properly initialise m_F_wc. Fixes issue #37
=> Fix warning: array subscript is above array bounds.

build_linux/Makefile-nlopt
nlopt is an external library, so there is not much point reporting warnings in this directory. Also disable -Wdeprecated-declarations.
=> * build_linux/Makefile-nlopt (CFLAGS): Remove -Wall.

build_linux/Makefile-sdktool, build_linux/Makefile-tcsconsole
The -Werror option can now be added for sdktool and tcsconsole directories.
=> * build_linux/Makefile-sdktool, Makefile-tcsconsole: Add -Werror now.

solarpilot/Flux.cpp, solarpilot/SolarField.cpp
`TOD` was moved down to its location of use to ensure it is initialised just before use.
=> Initialise some variables to suppress '<variable> may be used uninitialized in this function' warnings.

ssc/cmod_pvwattsv0.cpp, tcs/fmin.cpp
I grepped and found a number of floating point literals that were being needlessly cast to `double`. If a `float` literal is passed to a function with a `double` argument, the type of the literal will be promoted to `double' and the cast is not necessary.
We should aim to eliminate all of the C-style casts in the long run, favouring static_cast<>.
=> Remove needless casts to double

solarpilot/SolarField.cpp
This change re-enables the asserts to fix two warnings in the solarpilot directory:
../solarpilot/SolarField.cpp: In member function ‘void SolarField::cornfieldPositions(std::vector<sp_point>&)’:
../solarpilot/SolarField.cpp:2927:15: warning: ‘x_max’ may be used uninitialized in this function [-Wmaybe-uninitialized]
while(x_loc <= x_max){
^
../solarpilot/SolarField.cpp:2894:14: warning: ‘y_max’ may be used uninitialized in this function    [-Wmaybe-uninitialized]
while(y_loc <= y_max)
Assertions are convenient for telling GCC's value range analysis that `shape` is guaranteed to be in the range [0, XY_FIELD_SHAPE::UNDEFINED].  GCC can then determine that all `enum` cases are handled in the switch and, therefore, `x_max`/`y_max` is always be initialised by one of the cases.
=> Re-enable asserts to fix the solarpilot warnings

sdktool/editvariable.cpp
../sdktool/editvariable.cpp:276:9: error: comparison of unsigned expression < 0 is always false  [-Werror,-Wtautological-compare]
if (nr < 0 || nc < 0) return;
~~ ^ ~
../sdktool/editvariable.cpp:276:19: error: comparison of unsigned expression < 0 is always false [-Werror,-Wtautological-compare]
if (nr < 0 || nc < 0) return;
~~ ^ ~
=> Fix all warnings in sdktool

build_linux/Makefile-shared, shared/lib_weatherfile.cpp, shared/lib_windfile.cpp, shared/lib_windfile.h
This set of patches eliminates the use of the C fgets() function in favour of C++ streams. This eliminates lots of error-prone pointer arithmetic. This eliminates the last of the G++ warnings, so the last patch in this set enables -Werror.
Note that I renamed `locate` to `split` (as that is what it does!) and removed the arbitrary limitation on the maximum number of columns that can be handled.
=> Remove fgets

ssc/cmod_solarpilot.cpp
Replacing old code that was removed during compiler warning cleanup. Calls were needed to allocate arrays for output, even though return pointers weren't used and were causing warnings.
=> solarpilot layout and optimization failing

solarpilot/Land.cpp
fixes negative land area calculation for land with radial bounds and no inclusions
=> SolarPILOT land bounds fix for arrays without inclusions

solarpilot/AutoPilot_API.cpp
Fixes #141. Moved _inst outside of AutoOptHelper and renamed to avoid namespace conflicts. This fix is required for support of VS 15.6.1.
=> VS2017 compiler update - solarpilot issue

solarpilot/SolarField.cpp, solarpilot/SolarField.h
Several methods are needed to fully update after the layout has been modified. These are now in a single method that is called after layout, or after the layout has been altered. Fixes #149.
This change does not appear to affect SAM.
=> SolarPILOT post-layout calculations in a method

.vscode/c_cpp_properties.json, .vscode/launch.json, .vscode/tasks.json
This creates project files in the folder ".vscode" in the main project directory. These files configure the build to use the default makefiles, and provide a launcher for debugging. Fixes #147.
I have only tested this on one Ubuntu 16.04 machine (native). It would be helpful for others to review and see where things need to be generalized.
=> VSCode project files

shared/6par_newton.h, shared/6par_solve.h
The numerical [solver](http://www.aip.de/groups/soe/local/numres/bookcpdf/c9-7.pdf) (globally convergent newton method) is very sensitive to initial guesses. Effect on convergence due to differing initial guesses for each of the 6 parameters and uniqueness of convergent solution was explored over the search space. 
Due to large difference in magnitude of the parameters (1e-17 to 1e3), rescaling of the problem to unity was attempted but did not have any effect on convergence.
Since convergence was found to be dependent primarily on initial guess of 'a', the ideality factor, the method of iterating over different values of initial guesses for 'a', the same process which is currently done for Amorphous type modules, was implemented for CdTe type. 
For the given module specifications, …
=> Fix module coefficient generator for CdTe modules

solarpilot/mod_base.h
This bugfix improves type compatibility within the solarpilot module.
=> Bugfix: return SP_DATTYPE

shared/lib_shared_inverter.cpp, shared/lib_shared_inverter.h, ssc/cmod_pvsamv1.cpp
Adds an output (in data tables, not metrics table) for a capacity factor based upon the nameplate AC capacity of the system.  Calculation is: `capacity_factor_ac = annual_energy_ac / nameplate_ac`.
This references: https://github.com/NREL/SAM/issues/103.
To demonstrate, consider residential PV system with:
SAM calculates:
=> Add output for AC capacity factor

shared/lib_pv_io_manager.cpp, shared/lib_pv_io_manager.h, ssc/cmod_pvsamv1.cpp
Added flag class to lib_pv_io_manager.h as a wrapper for a bool/int value that is used for equality comparisons in pv_io_manager. The class implements an initialization check before each comparison is evaluated. Common comparison usages such as (flag), (flag == x) and (flag != x) overloaded with initCheck.
Mostly follows https://www.artima.com/cppsource/safeboolP.html. Disallowing comparisons to other types using templated overload was not used in order to allow comparisons given implicit conversion of enum values to int (otherwise a comparison with an enum could use both the int and templated version, resulting in error).
Since the flag class is intended for *_IO_Managers, I left it in lib_pv_io_manager.h for now. Perhaps if we had several *_IO_Managers in the future, then we could …
=> flag class for pv_io_manager using safe bool idiom

shared/lib_pv_io_manager.cpp, shared/lib_pv_io_manager.h, ssc/cmod_pvsamv1.cpp
This pull request attempts to make it less likely that a programmer will inadvertently try to use or assign to un-allocated outputs by forcing the allocation process to occur for all structures at the end of the construction of PVIOManager.
This pull request also creates an intermediate variable to store the lifetime dc degradation factor, which was previously being allocated at an output but calculated directly in the constructor of the PVSystem.  This was problematic once all output allocation was moved to to the end.  Typically outputs should be calculated with the compute module itself (pvsamv1), not in the IOManager, which is responsible for setting up inputs to the model and allocated the memory required for storing outputs.
=> Fixes NREL/SAM#25

.gitignore, shared/lib_mlmodel.cpp
Fixes #229, #227 and provides a short-term fix for #228. For now, changed ml model so that it calculates efficiency like the other models, i.e. 
eff = P / (module_area * POA_shaded_soiled)
However, the larger question of how module efficiency _should_ be calculated consistently remains open.
=> fix(): Address bugs and increase usability of ml module model

shared/lib_irradproc.cpp, shared/lib_pv_io_manager.cpp, test/shared_test/lib_irradproc_test.cpp
Updated previous fix to be a more robust fix for sunrise and sunset calculations at high latitudes. This includes calculating sunrise and sunset correctly and allowing power to be calculated when the sunset occurs on the next day (e.g. sunset is at 1:30AM from the previous day, sunrise is at 2:30AM that day). Added a test for the days where the high latitude locations proved problematic. In this update, also changed the nighttime sun angles that are reported so that they represent real values calculated at the actual time in question, and updated the NightCase irradproc tests accordingly (previously, the angles were either set to -999 or leftover values from calculating at noon that day).
I would appreciate a review on these changes and some testing by @cpaulgilman to confirm that they …
=> Updates to fix sunrise/sunset bug at very high latitudes

.gitignore, build_osx/config.status, shared/lib_pv_io_manager.cpp, shared/lib_pvshade.cpp, shared/lib_pvshade.h, ssc/cmod_pvsamv1.cpp, ssc/cmod_pvwattsv1.cpp, ssc/cmod_pvwattsv5_lifetime.cpp
There are 3 major updates in this PR:
- Resolve Issue #236 by applying the currently existing diffuse self-shading model in all scenarios
- Improve the diffuse self-shading algorithm so that the results more closely match PVsyst
- Correct miscalculation of self-shading albedo derate
After making the necessary changes so that diffuse self-shading could be applied to SAT systems, I ran a representative simulation and compared the self-shading diffuse derate to that calculated for the same scenario in PVsyst:
_5MW Backtracking SAT system in Oregon with 355 Mono modules (ML model) and a 30% GCR_
Below are the results:
The results show poor agreement that varies along with the magnitude of the derate.
In order to improve the agreement with the PVsyst model, I implemented the [PlantPredict …
=> feat(): Apply diffuse self-shading in all racking/shade-behavior scenarios and improve self-shading algorithm

test/ssc_test/cmod_tcsmolten_salt_test.cpp
Hey @Matthew-Boyd , just a quick update to the cmod_tcsmolten_salt_test.cpp outputs to be tested against. Since a pull and merge to my machine, the tests were failing due to the code being changed. They should all pass now. 
NOTE: The Rankine_Evap_Condenser_SingleOwner test was still producing incorrect outputs where this configuration should be scrutinized. See below. These irregular outputs were still updated with new irregular outputs to pass the test, however do not reflect realistic values.
* "annual_energy" = -1.88859e7
* "capacity_factor" = -2.08302
* "kwh_per_kw" = -182.472
* "conversion_factor" = 0
=> Update molten salt power tower model outputs 

test/ssc_test/cmod_pvwattsv7_test.cpp
While setting up the unit test framework, I got an error on LifetimeModeTest_cmod_pvwattsv7 due to a mismatch in lengths. Correct the mismatch so all three relevant variables are the same.
=> Match array length where it does not match analysis period

ssc/cmod_pvsamv1.cpp
Fixes a typo (#344) where a += was actually an =, which decreased the clipping losses displayed in SAM.
=> Fix inverter clipping display issue 344

shared/lib_battery.cpp, test/shared_test/lib_battery_test.cpp
Due to an operator precedence error (% occuring before /) subhourly table based simulations were degrading faster than specified. Fix this issue and add a test.
To test: run SAM with the files from https://github.com/NREL/SAM/issues/291. Hourly degradation should match subhourly.
=> Fix SAM issue #291, calendar degradaton specified in a table

ssc/cmod_pvwattsv7.cpp, test/input_cases/pvwattsv7_cases.h, test/ssc_test/cmod_pvwattsv7_test.cpp
Thanks to detailed error reporting in NREL/SAM#295, the lack of bifaciality effect on the power was found to be due to bifacial simulations decreasing total POA, thereby reducing gains.
The total POA was reduced since the module cover loss was accurately calculated using just front side irradiance, but then a multiplier `f_cover` to the `poa_for_power` value was calculated incorrectly. 
With bifacials, `f_cover`, the ratio between the post-module cover `tpoa` and the original `poa`, was lowered since the denominator was front + rear rather than just front. 
This led to smaller gains in power as calculated by `poa_for_power *= f_cover * f_AM;`
Updated test to show `annual_energy_bi/annual_energy_mono` > 1.04
=> Pvwatts bifacial

test/ssc_test/cmod_windpower_test.cpp
`cmod_wind_landbosse` tests currently causing SSC tests to fail since python isn’t hooked up properly.
Disable (for now) when python configuration isn't set up.
=> turn off landbosse tests if python isn't correctly set up

ssc/cmod_swh.cpp, test/ssc_test/cmod_swh_test.cpp
As came up earlier in the year for rEV, this adds the ability for solar water heating compute module to directly use solar resource data instead of a file.
=> Weatherdata for Solar Water Heating

ssc/cmod_pvwattsv7.cpp
Comments in the labels field to address https://github.com/NREL/pysam/issues/31
Questions for review:
(1) Will this break anything?
(2) Should I give pvsamv1 the same treatment?
(3) Is there any easy way to get high level comments like I put at the top of the file into the readthedocs output? Nate had some PVWatts usage recommendations he wanted to include based on this, which I added to the cpp file. Is there a better spot for this?
=> Comments for pysam

ssc/cmod_pvwattsv5.cpp, ssc/cmod_pvwattsv7.cpp, ssc/vartab.h
Expose "gen" in var table as lifetime system power output. Originally hidden since lifetime PVWatts was not used in GUI since the degradation isn't explicitly simulated, but now that it is being used in the GUI, the variable should be listed for export.
Addresses issue NREL/pysam#31. Also see #371
=> add "gen" as output to PVWatts

ssc/cmod_pvsamv1_eqns.cpp
Allow hourly, 30 min and 15 min load and critical load profiles as input to SAM's Size battery from Reopt function.
close NREL/sam#310
=> allow reopt sizing to use subhourly load profiles

ssc/cmod_pvwattsv7.cpp
pvwatts7 was throwing an error when run in a subhourly fuel cell configuration (see https://github.com/NREL/SAM/issues/315). Fix the error by migrating from accumulate_monthly to accumulate_monthly_for_year.
It looks like this solves a second bug, where even on an hourly fuel cell configuration, all of the energy was being placed in January. Before fix:
After fix:
Mysteries: why did pvwattsv7 work subhourly without the fuel cell?
Questions: do any additional instances of accumulate_monthly need to change?
=> Sam 315 energy accumulation fuel cell

ssc/cmod_pvwattsv5.cpp, test/ssc_test/cmod_pvwattsv5_test.cpp
Copying comment over from #385 :
It looks like the Pvwattsv5 single time step model wasn’t correctly updated with some recent refactoring.
I fixed this by calling initializing functions from base pvwattsv5 class in the pvwattsv5_1ts: 4ef0b09
Regarding poa and tcell, a comment says 
>/* input/output variable: tcell & poa from previous time must be given */
but these values are not used in the code.
It looks like they could be used as part of `initialize_cell_temp`, which can use `poa` and `tcell` from the last time step.
Question for @janinefreeman, should `poa` and `tcell` of the last time step be required/used? If not, should they not be "required inputs", since users may not have these values to start?
=> Pvwattsv5 1ts

ssc/vartab.cpp
The code is correct, but the indenation makes it misleading (and G++ agrees!)
```
vartab.cpp: In member function ‘var_data* var_table::lookup(const string&)’:
vartab.cpp:322:5: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
322 |     if (it == m_hash.end())
|     ^~
vartab.cpp:324:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
324 |  if ( it != m_hash.end() )
|  ^~
```
=> Re-indent var_table::lookup to eliminate G++ misleading-indentation warning

ssc/cmod_fuelcell.h
=> Reorder some fuelCellVariables members to avoid G++ reorder warning

ssc/cmod_sco2_design_point.cpp
Fix warnings of this form by catching the exception by reference instead:
```
error: catching polymorphic type ‘class C_csp_exception’ by value [-Werror=catch-value=]
```
=> Fix warnings about catching exception by value

nlopt/CMakeLists.txt
Use add_compile_options() in `nlopt/CMakeLists.txt` to set the options correctly on non-MSVC platforms. Appending to `CMAKE_CXX_FLAGS` is not appropriate for this directory as it contains C source files, not C++.
=> Use add_compile_options to set nlopt options correctly

test/shared_test/lib_battery_test.cpp
I'm not sure how this ever worked :smile:
Maybe it works on Visual Studio, but it doesn't work on G++ without <cmath> to declare `fabs`, `fmax`, `fmod`, etc.
=> Include <cmath> for fabs, fmod, fmax, etc.

ssc/CMakeLists.txt
For selected compilation units that contain static documentation strings that are never referenced, pass `-Wno-unused-variables`. There is no easy way to fix this other than silencing the warning on a restricted basis.
=> Pass -Wno-unused-variables for some files

ssc/cmod_generic_system.cpp, ssc/cmod_pvsamv1.cpp, ssc/common.cpp
https://github.com/NREL/SAM/issues/335
In common.cpp, make dc_adjust:constant required, and :hourly and :periods optional. This is consistent with the adjustment_factors setup() function that requires :constant.
Remove dc_adjust from generic_system. SAM UI does not assign a value to dc_adjust for the generic system configurations. Maybe this was added for some internal testing of DC losses for a generic system / battery configuration.
Change pvsamv1 label for adjust to "AC adjustment".
=> Fix dc_adjust issue SAM_335

ssc/cmod_pvsamv1.cpp
The transformer timestep units were previously in kWh and are now in kW
=> ssc issue 400 transformer timestep loss units updated.

shared/lib_battery.cpp, shared/lib_battery.h, test/shared_test/lib_resilience_test.cpp
Fixes:
- Copied over some fixes from `develop` on `calculate_max_charge_w` and `calculate_max_discharge_w`
- fix `-inf` potential from `voltage_model`
- voltage drop across aggregated stack the same for charge or discharge
- adapt test to show catch difference in using abs(I_string)
With the thermal model turned off: this is the yearly battery charging & discharging table:
=> Vanadium flow battery: voltage model fixes

shared/lib_util.cpp, shared/lib_weatherfile.cpp, shared/lib_weatherfile.h, ssc/common.cpp, ssc/common.h, test/ssc_test/cmod_pvsamv1_test.cpp
The subhourly weather file [here](https://raw.githubusercontent.com/NREL/ssc/develop/test/input_cases/pvsamv1_data/LosAngeles_WeatherFile_15min.csv) used in `CMPvsamv1PowerIntegration_cmod_pvsamv1.NoFinancialModelCustomWeatherFile` counts the hours with (1-24) instead of (0-23).
If weather_record.hour is being used to calculate index, as in this code: 
https://github.com/NREL/ssc/blob/3c8195d35cbf75372ab3f77653fcd2a47be9c57a/ssc/cmod_pvsamv1.cpp#L1131
then, hour ranges should always be (0-23)
I assumed the weather file starts "recording" at the same time, but perhaps just has different indexing, so I subtracted `1` from each hour. This ended up shifting the interpretation of the data and resulted in the test changes shown in the commit.
Should these types of files be handled differently?
=> Hour ranges in weather file / data

ssc/cmod_pvwattsv7.cpp
The pv.modules on line 537 was zero for all dc_nameplate values less than or equal to the module.stc_watts = 300. Also, the pv.modx calculation on line 559 was zero. These two conditions caused the ssout.shade_frac_fixed to be calculated as -inf (line 956) which in turn caused the ibeam to be nan on line 981. 
The fix was to check both pv.modules >=1 (line 539) and pv.nmodx>=1 (line 561).
=> Allow output for 300W and under system capacities for pvwattsv7

ssc/cmod_grid.cpp, ssc/common.cpp
An alternative solution to the issue in #416. Allows three options for load_escalation and other scaling factors:
* Length zero: no scaling (multiply by 1.0)
* Length 1: scale at a constant percent rate each year
* Length n_years/analysis_period: scale based on the custom vector
Defaults to analysis_period of 1 year if it is not defined, preventing the access errors.
=> Resolve PVWatts issues by making scalefactors more flexible

ssc/cmod_fuelcell.cpp, ssc/cmod_pvsamv1_eqns.cpp, ssc/cmod_tcsmolten_salt.cpp, ssc/cmod_test_ud_power_cycle.cpp, ssc/cmod_utilityrate5.cpp
Picked up by G++ once I locally disabled `-Wunused-variables`.
=> Remove unused variables

ssc/core.cpp
This function returns `bool`, but falls off the bottom of the function without a return value.
=> core.cpp (compute_module::evaluate): Return true if all OK

shared/lib_time.cpp, shared/lib_time.h, ssc/cmod_battery.cpp, ssc/cmod_battwatts.cpp, ssc/cmod_grid.cpp, ssc/cmod_pvsamv1.cpp, ssc/cmod_swh.cpp, test/shared_test/lib_time_test.cpp, test/shared_test/lib_time_test.h
See https://github.com/NREL/ssc/issues/426 for background. This was introduced to develop with https://github.com/NREL/ssc/issues/411, I haven't been able to reproduce it on patch because patch is strict about making sure load and gen are the same length, and pvsamv1 used a different method for load forecasting.
As far as I can tell, single_year_to_lifetime_interpolated is only used on data with units of power, therefore removing it the interpolation factor is appropriate for the current code. If we apply this to energy or other units, we may need to pass it in as a parameter in the future.
=> Remove interpolation factor from single_year_to_lifetime_interpolated

shared/lib_time.cpp, ssc/cmod_battery.cpp, test/ssc_test/cmod_pvsamv1_test.cpp
In `cmod_battery`, adding an error check for when the `gen` input is single year rather than lifetime. This leads to `dt_hour > 1` and `step_per_hour = 0` which caused a segfault in `single_year_to_lifetime_interpolated`.
This won't happen in SAM but can be a mysterious hard crash in PySAM.
=> Add check for dt_hour > 1 and step_per_hour == 0

shared/lib_battery_voltage.cpp, shared/lib_battery_voltage.h, ssc/cmod_battery.cpp, test/shared_test/lib_battery_dispatch_automatic_btm_test.h, test/shared_test/lib_battery_dispatch_automatic_fom_test.h, test/shared_test/lib_battery_dispatch_manual_test.cpp, test/shared_test/lib_battery_dispatch_manual_test.h, test/shared_test/lib_battery_test.cpp, test/shared_test/lib_battery_test.h, test/shared_test/lib_battery_voltage_test.cpp, test/shared_test/lib_battery_voltage_test.h, test/shared_test/lib_resilience_test.cpp, test/ssc_test/cmod_battery_pvsamv1_test.cpp, test/ssc_test/cmod_battery_stateful_test.cpp, test/ssc_test/cmod_battery_stateful_test.h, test/ssc_test/cmod_battwatts_test.cpp
Changes:
- Remove error for battery timesteps less than a minute
- Update initial guesses for `calculate_max_discharge_w`, `calculate_max_charge_w` and `calculate_current_for_target_w` for each voltage model when applicable
- Add new `SubMinute` tests to dynamic voltage model, voltage table and vanadium voltage classes for 1/200 or 1/360 `dt_hr`
- Modify a test result from `CMBattwatts_cmod_battwatts, ResidentialDefaultsLeadAcid`-- difference is due to change in initial guesses but not sure of the details
close #432
=> Batt subminute

ssc/cmod_battery.cpp
As @cpaulgilman requested in https://github.com/NREL/SAM/issues/341, SSC now throws an error if a user inputs a value greater than 6 for dispatch periods.
To test:
- Run PV-battery residential with the defaults, it should complete successfully
- Put a number > 6 in the weekday schedule. Running the simulation should throw an error about the weekday schedule
- Revert the weekday schedule, put a number > 6 in the weekend schedule. Running the simulation should throw an error in the weekend schedule
- Revert the weekend schedule. The simulation should complete successfully
=> Improve manual dispatch error handling

ssc/core.cpp, ssc/core.h, ssc/ssc_equations.h
Enabling & reviewing @Matthew-Boyd's `compute_module::exec()`'s call to new `evaluate` function that calls `ssc_equations` so that all interdependent inputs are correctly modified. Nice job!
This is part of the push to migrate equations and callbacks that modify SSC inputs from the GUI. This allows SDK and PySAM users to modify compute_module inputs without worrying that they are missing variable updates and logic in the GUI.
This works by looking up all ssc_equations that apply to a given cmod by matching the name-- hence a new name field to `compute_module`.
Added a field to `ssc_equation_entry` called `auto_eval` for equations that should be run in the `evaluate` loop. https://github.com/NREL/ssc/blob/1c065b2e53e99391e906c90e6ab2d8194378fff1/ssc/ssc_equations.h#L42
@Matthew-Boyd, could …
=> Dependent inputs

test/shared_test/lib_battery_voltage_test.cpp
Not sure why this header isn't needed on other platforms. For a C++11 compiler, the standard says `<cmath>` must be included.
=> Include <cmath> for fabs()

shared/lib_battery.cpp, test/shared_test/lib_battery_test.cpp, test/shared_test/lib_battery_test.h
The previous version of the thermal model could be numerically unstable at small timesteps and large currents, due to the current term not having an exponential to smooth it. This update includes the current term in the exponential, such that the battery will approach the same steady state temperature at large and small timesteps.
Old behavior, 10 second timesteps:
New behavior:
Reference for converging to steady state temperature: https://web.mit.edu/16.unified/www/FALL/thermodynamics/notes/node129.html (the convection constants are different, but the underlying differential equations are the same)
=> Subminute thermal model

ssc/cmod_utilityrate5.cpp
As discussed in https://github.com/NREL/SAM/issues/358, time series buy and sell rates don't run when net metering is chosen as a metering/billing option. Add an exception in case a user tries to enable both in PySAM/the SDK. 
To trigger this exception with the GUI:
* Build this branch with patch
* Switch to net billing and enable time series rates
* Switch back to net metering
* Run the simulation
This exception will not be encountered from the GUI when the parallel SAM PR is complete.
=> SAM 358: add exception for time series and net metering

shared/lib_weatherfile.cpp, shared/lib_weatherfile.h
Throw an exception for any weatherfile subject to issue https://github.com/NREL/ssc/issues/447
The exception occurs when running a simulation with an old interpolated weather file for all relevant cases, and if https://github.com/NREL/SAM/pull/364 is checked out, it will appear when selecting interpolated weather file on the battery modules.
To test:
- Check out and build SAM on this branch
- Select an interpolated weather file from 2020.2.29 r3 (or develop prior to today) and try to run it
- An exception should be raised about hour 0 occurring after hour 23 (or similar)
Weather files interpolated with the code on https://github.com/NREL/SAM/pull/364 should not trigger the exception.
=> Throw exception if weatherfile goes backwards in time

ssc/cmod_battery.cpp
Add code to cmod_battery to take a battery temperature array from length 1 and resize it to length nrec.
Note that this will not solve https://github.com/NREL/ssc/issues/472 by itself, since the UI is still providing an array of length nrec. See https://github.com/NREL/SAM/pull/418 for details. I'm open to changing things on the SAM side if desired, but figured this code would simplify PySAM inputs.
=> add code to resize temperature array from length 1 to length nrec

shared/lib_battery_lifetime.cpp
-Add initialization for relative capacity when Calendar setting is set to None
-Closes #478
=> Battery Calendar Model set to None results in Cap % > 100

shared/6par_solve.h, test/shared_test/6par_solve_test.cpp
Fixed the failing modules from @cpaulgilman's helpful spreadsheet by 
1. Increasing the allowable Light Current parameter, Il, from 15 A to 20 A. This fixed the newer, higher power and higher voltage modules, which all had Il around 18 A. It makes sense that the induced current is greater in these modules.
2. Codified original workaround of switching to "multiSi" technology to get failing modules to solve. This works because the "multiSi" technology uses the "default" set of initial guesses, which were created via regression from an old CEC database.
In the future, we may need to update these regressions for generating a working initial guess with the newest, expanded CEC database.
Included a SAM file with each module's IV curves. …
=> Update 6par Module Model Parameter Generator

.lgtm.yml, .travis.yml, CMakeLists.txt, ssc/CMakeLists.txt
CMake option names should be prepended to avoid potential name collisions when SAM source code is included in other projects.
=> CMake Options Prepend with "SAM"

ssc/cmod_utilityrate5.cpp
Remove output added in https://github.com/NREL/ssc/pull/483. After trying to write the help documentation, @cpaulgilman and I determined it will be easier to direct user so the "electricity rate data by tier and period" variables.
=> Remove net metering rollover credits output

ssc/cmod_pvsamv1_eqns.cpp, test/ssc_test/cmod_pvsamv1_test.cpp
Pairs with https://github.com/NREL/SAM/pull/445 to streamline how the SAM-ReOpt integration passes subhourly data
=> ReOpt: use time_steps_per_hour input

shared/lib_battery_dispatch.h, shared/lib_battery_dispatch_automatic_btm.cpp, shared/lib_battery_dispatch_automatic_btm.h, ssc/cmod_battery.cpp, test/ssc_test/cmod_battery_pvsamv1_test.cpp
Two tweaks to the price signals dispatch code based on feedback from our beta testers:
- Update the dispatch planner to better match the powerflow calculations. This allows DC connected systems to charge from PV even if the load is greater than generation at that timestep
- Return the cycle degradation cost in $/cycle-kWh such that the output and input have the same units.
=> Price signals dispatch feedback

ssc/cmod_utilityrate5.cpp
The if statement for time series buy rates re-initialized the variables cnt and ts_br, such that the values read out of the vartable never make it to the setup_rate_data function. Thus, the length of rate.m_ec_ts_buy_rate was always 0, and the flat rates were used instead.
Can be tested with the SAM file attached to https://github.com/NREL/SAM/issues/494, closes https://github.com/NREL/SAM/issues/494
=> Fix time series buy rates

CMakeLists.txt
Fix SSC issue #505 that breaks the install targets of projects that include this project.  EXCLUDE_FROM_ALL will prevent the jsoncpp install target without breaking other projects.
=> Fix for SSC issue #505

shared/lib_pvshade.cpp
Fixes unhandled divide by zero error when pv tilt = 0 for some builds
close #511
=> Unhandled Divide by Zero Error

shared/lib_battery_dispatch_automatic_btm.cpp, shared/lib_utility_rate.cpp, shared/lib_utility_rate.h, test/shared_test/lib_battery_dispatch_automatic_btm_test.cpp, test/shared_test/lib_utility_rate_test.cpp, test/ssc_test/cmod_battery_pvsamv1_test.cpp
Incorporates several improvements to price signals dispatch to better handle demand charges.
Previously, the price signals dispatch algorithm would ignore peaks on the last day of each month in order to dispatch at midnight, due to a perceived high price for each month's initial load. The forecast function was using net load to forecast demand charges, so the forecast load was lower than typical night time loads. Increase the prediction to average gross load, so that the algorithm waits for higher peaks.
Additionally, anticipate demand charges in future hours by planning additional dispatch in hours with higher net grid use than the highest cost hour. Previously, the 2nd hour of high power would show a much lower cost than the first, leading the algorithm to plan a smaller dispatch, but …
=> Price signals dispatch improved demand

test/shared_test/lib_battery_dispatch_automatic_btm_test.cpp, test/shared_test/lib_battery_dispatch_automatic_btm_test.h, test/shared_test/lib_battery_dispatch_manual_test.cpp, test/shared_test/lib_battery_dispatch_manual_test.h
Battery capacity was set to a separate variable that made the capacity and voltage model have different capacities.
Modify capacity model to use the same value, adjust the expected values.
=> fix battery capacity in lib_battery_dispatch_automatic_btm_test.h

shared/lib_battery_voltage.cpp, shared/lib_battery_voltage.h, test/shared_test/lib_battery_dispatch_manual_test.cpp, test/ssc_test/cmod_battery_pvsamv1_test.cpp
-Change set_initial_SOC for dynamic voltage model to use battery capacity rather than cell capacity, as updateVoltage() divides by the number of strings to get to cell capacity. 
-Closes #520
=> Set initial SOC for voltage with battery capacity rather than cell

ssc/cmod_utilityrate5.cpp, test/ssc_test/cmod_utilityrate5_test.cpp
Tracks the surplus and deficit tiers (they can be different) differently for net billing and buy all / sell all. This code will correctly allocate kWh to lower tiers before moving on to upper tiers.
Utility rate:
Behavior in 2020.11.29: 
Behavior in this PR:
Test file available in https://github.com/NREL/ssc/issues/535
=> Ssc 535 fix tiers net billing

shared/lib_battery_voltage.cpp, ssc/cmod_battery.cpp, ssc/core.cpp
-Better fix to #517 
-Do we need a catch in battery_stateful as well? If so where?
-Closes #517
=> Moved dynamic voltage model error checking

shared/lib_battery_dispatch.cpp, test/shared_test/lib_battery_dispatch_automatic_btm_test.cpp, test/ssc_test/cmod_battery_pvsamv1_test.cpp, test/ssc_test/cmod_battwatts_test.cpp
Two changes: First - pull adjustments out of else-if chain to ensure they are applied consistently. This also helps increase charging targets in price signals dispatch. Second, adjust the custom dispatch targets if they are too high, reducing iteration. Adjust tests as needed
- Includes a new test to trigger this specific bug
- Changes to two other custom dispatch tests were expected
- Price signals dispatch now has better access to charging power, due to a related constraint in the if-else chain
- The BattWatts changes were unexpected, but justified when I checked the tests in the debugger
=> Better enforce "don't export to grid" constraints

shared/lib_pv_io_manager.cpp, ssc/cmod_pvsamv1.cpp, ssc/cmod_pvwattsv7.cpp
Adding minute to PV and PVWatts model irradiance error messages that show timestep m d y h.
Fixes SAM Issue 584: https://github.com/NREL/SAM/issues/584
=> Add minute to PV irradiance processor error messages

shared/lib_utility_rate_equations.cpp
Solves https://github.com/NREL/SAM/issues/563 - the variable to set the number of tiers in a month was being reset for each period, rather than enforcing the number of tiers in the first period of the month. This produces an existing error message in the SAM file attached to the bug, and responds correctly to different months having different numbers of tiers.
=> ensure num_tiers is enforced for the first tier of each month

shared/lib_irradproc.cpp, ssc/cmod_pvsamv1.cpp
When a PV module has an area of 0, the calculated dimensions of the module lead to erroneous behavior in the self-shading and bifacial calculations. Catch this error in pvsamv1 and irradproc.
Close #562
=> Add error checks for when PV module dimensions are 0

ssc/cmod_cashloan.cpp, ssc/cmod_equpartflip.cpp, ssc/cmod_fuelcell.cpp, ssc/cmod_host_developer.cpp, ssc/cmod_levpartflip.cpp, ssc/cmod_merchantplant.cpp, ssc/cmod_pvsamv1.cpp, ssc/cmod_saleleaseback.cpp, ssc/cmod_singleowner.cpp, ssc/common.cpp
-Added assignment checks to only output fuel cell and battery OandM and replacement cost outputs when there is a fuelcell or battery, respectively
-Removed battery efficiency, AC loss, and DC loss for cases without a battery
-Closes https://github.com/NREL/SAM/issues/510
-Closes https://github.com/NREL/SAM/issues/448
=> Remove fuelcell and battery outputs from cases without those systems

shared/lib_battery_dispatch_automatic_btm.cpp, test/shared_test/lib_battery_dispatch_automatic_btm_test.cpp, test/ssc_test/cmod_battery_pvsamv1_test.cpp
Decrease the value of stored energy so things perform better in situations where manual dispatch performs well. Now out performing manual by $500 (out of $3.6M), a 1.4% improvement over the previous dispatch.
=> tweaks to price signals dispatch for the pvsc paper. 

ssc/cmod_battery.cpp, ssc/cmod_battwatts.cpp, ssc/cmod_grid.cpp, ssc/cmod_pvsamv1.cpp, test/ssc_test/cmod_battery_test.cpp, test/ssc_test/cmod_battwatts_test.h
Pairs with SAM PR https://github.com/NREL/SAM/pull/641
First inputs in the vartable for the grid outage work. Want to get this merged sooner to avoid conflicts in defaults files.
=> add grid_outage and run_resiliency_calcs to vartable

ssc/cmod_cashloan.cpp, ssc/cmod_equpartflip.cpp, ssc/cmod_host_developer.cpp, ssc/cmod_levpartflip.cpp, ssc/cmod_merchantplant.cpp, ssc/cmod_saleleaseback.cpp, ssc/cmod_singleowner.cpp, ssc/common_financial.cpp, ssc/common_financial.h
-Added array size checks for sub-hourly simulations
-Added check for schedule or array ppa multiplier model to build array
-Using var table inputs now rather than extra input in lcos_calc function; Removed extra variable
=> TOD multipliers for LCOS calculations

ssc/common.cpp
Function to check whether solar resource data is continuous was incorrectly stepping through minutes and leading to false negative for a valid 5 min file.
see https://github.com/NREL/pysam/issues/88
=> fix check_continuous_single_year

ssc/cmod_cashloan.cpp, ssc/cmod_equpartflip.cpp, ssc/cmod_fuelcell.cpp, ssc/cmod_fuelcell.h, ssc/cmod_host_developer.cpp, ssc/cmod_levpartflip.cpp, ssc/cmod_merchantplant.cpp, ssc/cmod_saleleaseback.cpp, ssc/cmod_singleowner.cpp, ssc/common.cpp, ssc/common_financial.cpp
-Added 0.001 scaling for om_batt_variable_cost and om_fuelcell_variable_cost to use $/MWh inputs from GUI
-Added calculations for annual variable production costs based on battery annual discharged energy and new fuelcell annual energy out variable
-Removed cost by energy calculations for battery variable OM costs from LCOS calculations to pass already calculated cash flow from financial models instead
-Changes carried over to all financial models
=> Variable production O&M cost changes for battery and fuel cell

test/ssc_test/cmod_battery_pvsamv1_test.cpp
Follow on to https://github.com/NREL/ssc/pull/611 - the Windows value got out of tolerance with the changes, but it didn't fail the PR since the Linux value was still within tolerance.
=> update price signals lifetime test value due to cycle degradation changes

shared/lib_battery_powerflow.cpp
A floating point error (~1e-15) was causing a stack overflow in the powerflow code. Add a tolerance to fix the issue.
Alternative fix would be to set gen to zero if it's smaller than some tolerance. I think "tolerance" in the powerflow code is too high for this approach, I'd want 1e-7 or smaller for this approach.
Test with
[Test_Case.zip](https://github.com/NREL/ssc/files/7246382/Test_Case.zip)
=> add tolerance to grid charging check to allow for floating point issues

ssc/common_financial.cpp
`cf_batt_replacement_cost` is a duplicate of `cf_battery_replacement_cost` in common.cpp
=> Delete cf_batt_replacement_cost duplicate

ssc/cmod_utilityrate5.cpp
-ur_calc_timestep updates tier_charge within hourly buy rates loop to avoid falling back on TOU rates
-Closes  https://github.com/NREL/SAM/issues/736
=> Fixed utilityrate to check for hourly buy rates 

shared/lib_windwatts.cpp, shared/lib_windwatts.h, ssc/cmod_windpower.cpp, test/ssc_test/cmod_windpower_test.cpp
The wind wake models would previously throw an error if >300 turbines were specified. Added an optional input to the SDK only, "max_turbine_override", that allows a user to specify a new number of maximum turbines. Added an associated test. All wind tests are passing with these changes. Fixes #628 .
=> Added optional override for max number of turbines

shared/lib_pv_io_manager.h, ssc/cmod_pvsamv1.cpp
This PR changes the way that we report errors about negative calculated irradiances from warnings to notices. Reporting these as warnings can cause SAM to crash because there are so many instances. This fixes NREL/SAM#610 and fixes NREL/SAM#416 .
=> Change warnings about negative calculated irradiance to notices

test/ssc_test/cmod_battery_pvsamv1_test.cpp
Add additional tests of battery lifetime to pin down issue https://github.com/NREL/ssc/issues/675 on price signals dispatch. Increase the tolerance for the price signals test until we can better nail down cross platform differences.
Will re-open https://github.com/NREL/ssc/issues/614 to solve after the release.
=> Addtl lifetime testing in integration tests

ssc/cmod_mhk_costs.cpp, ssc/cmod_mhk_tidal.cpp, ssc/cmod_mhk_wave.cpp
-Updated mhk_wave to compute per_kW cost metrics in addition to per_kWh metrics
-All output metrics now in var_table
-Allows for proper code generation in SDK tool
-Added check for cost variable assignment to output cost metrics (checking for non-financial cases)
-See https://github.com/NREL/SAM/pull/794
=> Marine energy metrics in ssc var_tables

ssc/common_financial.cpp
-Avoid error in LCOS BTM calculations by checking for 0 monthly grid charge before performing parasitic cost calculations
-Fixes https://github.com/NREL/SAM/issues/801
=> Added divide by zero check for BTM battery grid charging cost

test/ssc_test/cmod_battery_pvsamv1_test.cpp
GitHub Actions uses a new Linux version, which causes more drift in the test results vs Windows. Increase the tolerance until we have more time to debug https://github.com/NREL/ssc/issues/614
=> Ssc 614 increase tolerance again

shared/lib_geothermal.cpp
-Hour indexing corrected to go from 0-23 for the day rather than hourly years when the hourly option is selected in the UI
=> Power Block Hourly option causes hour of year indexing failure in Geothermal

shared/lib_battery_dispatch_automatic_btm.cpp, shared/lib_battery_dispatch_automatic_btm.h, ssc/cmod_battery.cpp, ssc/cmod_battery.h, ssc/cmod_pvsamv1.cpp, test/ssc_test/cmod_battery_pvsamv1_test.cpp
Fixes SAM issue https://github.com/NREL/SAM/issues/802
- Checks the chosen dispatch method prior to throwing an exception about forecast errors
- Uses the actual grid power for dispatch rather than the forecast grid power. This removes the effect of the forecast variables on input grid power targets
- This also increases the NPV of the "one day look behind" forecast option. Since only the grid power target uses the forecast now and the dispatch uses the actual grid power, the NPV increases by a factor of ~6 in the default commercial case (20% of the lookahead value to 90% of the lookahead value)
To test:
(1)
- Select a pv-battery behind the meter sytem
- Go to the dispatch options
- Select "custom weather file"
- Select "input grid power targets"
- Click on "edit values" next to "monthly …
=> Fix sam 802 forecast errors

tcs/ud_power_cycle.cpp
The User Defined Power Cycle model was using an incorrect equation to calculate the interaction effect for the high level of HTF mass flow rate. This bug only affects cases where the power option is set to the UDPC model, and as such does not influence default CSP cases that use the Rankine cycle model.
When applied to the default molten salt power tower case where the cycle model is changed to the default UDPC inputs, the annual energy increase 0.1%. The effect may be more significant if 1) your UDPC data includes more variation relative to the default data at m_dot_HTF > 1 or 2) your case increases the maximum HTF over-design above the default 1.05 value.
=> fix upper level m_dot effect calc

ssc/cmod_tcsmolten_salt.cpp
Makes transient receiver cmod outputs conditional on using receiver transient model. The transient model is only accessible through scripting, so these outputs were either undefined or always set to 0 in SAM. This commit removes these outputs when calling the molten salt power tower model through SAM.
=> make mspt transient rec outputs optional

tcs/csp_solver_two_tank_tes.cpp
only used as calculated design value on UI pages, so should not influence simulation results.
=> fix design point tes heat loss calc

tcs/csp_solver_two_tank_tes.cpp
only used as calculated design value on UI pages, so should not influence simulation results.
=> fix design point tes heat loss calc (#709)

shared/lib_shared_inverter.cpp, test/shared_test/lib_battery_powerflow_test.cpp
Fix the max efficiency function by multiplying by the number of inverters. Update tests for improved efficiency estimates accordingly.
Fixes #722
=> clean up max power eff function for large numbers of inverters

shared/lib_utility_rate_equations.cpp, shared/lib_utility_rate_equations.h, ssc/cmod_utilityrate5.cpp, test/ssc_test/cmod_utilityrate5_test.cpp
Pairs with SAM pull request https://github.com/NREL/SAM/pull/889
- Allows billing demand computations when there are only kWh/kW energy charges (no demand charges)
- Allows for kWh/kW energy charges to only show up in some months
Both of the above can be tested with the file attached to https://github.com/NREL/SAM/issues/857
=> Fix SAM 857 and 875

ssc/cmod_merchantplant_eqns.cpp, ssc/common.cpp, test/ssc_test/save_as_JSON_test.cpp
cmod_merchant_plant_eqns now delivers units of $/kWh to the battery dispatch code. This allows the automated battery controller battery to dispatch based on the price regardless of the cleared capacity. Introducing cleared capacity into the battery dispatch is scheduled for (the often delayed) https://github.com/NREL/sam/issues/181
Additionally, clean up the merchant plant error checking for cases where gen > cleared capacity.
Fixes https://github.com/NREL/ssc/issues/694
=> Fix ssc 694

ssc/cmod_pvsamv1.cpp
Fixes https://github.com/NREL/SAM/issues/856
The DC connected batteries need an estimate of loss percent for grid outages, but since some of the transformer load losses use *= the calculation was being applied twice. Reset the variables after the DC loss estimation to fix the issue.
Test by specifying a transformer load loss in a default case. An AC connected battery and DC connected battery should have similar transformer loss %s after running.
=> Fix ssc 856 xfmr losses

shared/lib_battery_dispatch.cpp
- Adjust battery charging for updated inverter efficiency and estimate unmet critical load in the dispatch
- Remove redundant dc-dc efficiency adjustments
Results in expected outage parametrics behavior: decreasing critical load unmet w/ increasing battery size:
=> Fix SSC 737 - improve dc outage charging

shared/lib_utility_rate_equations.cpp, shared/lib_utility_rate_equations.h, ssc/cmod_utilityrate5.cpp
- Initializes the demand charge used by year1_hourly_dc_with_system to zero to prevent negative values
- Only sets values in year1_hourly_dc_peak_per_period once each month, preventing redundant values. Should now be one value per TOU period
Closes #720
=> Fix SSC 720

ssc/csp_common.cpp
Rotating cavity receiver when plant is in the southern hemisphere.
Closes NREL/SAM/issues/898
North hemisphere: (3623 heliostats)
South hemisphere: (3650 heliostats)
Small difference is most likely caused by SolarPilot field layout algorithm.
If the northern hemisphere heliostat field is exported, flipped, and imported for the southern hemisphere case, the gap in annual energy is reduced.
=> Fixing SAM issue 898

ssc/cmod_cashloan.cpp, ssc/cmod_communitysolar.cpp, ssc/cmod_equpartflip.cpp, ssc/cmod_host_developer.cpp, ssc/cmod_ippppa.cpp, ssc/cmod_levpartflip.cpp, ssc/cmod_merchantplant.cpp, ssc/cmod_saleleaseback.cpp, ssc/cmod_singleowner.cpp, ssc/cmod_thirdpartyownership.cpp, ssc/common_financial.cpp
Use consistent values for cf_energy_net throughout the code - this should always just be "sum of gen." The previous code used "positive numbers in gen" for about half the time and then switched it after the PPA calculation loop. Fixing this required updating some values of cf_energy_net to cf_energy_sales. This calculation change and the associated labels changes should address Steve's comments in https://github.com/NREL/SAM/pull/927
The goal of this PR is that no numbers with units of $ should change at the end of the calculation. Changes in values with units of kWh for behind the meter systems are expected.
Note that there are some output names that need to be changed that aren't here. That seems out of scope for this PR, so I made a follow up issue: …
=> Confirm net means net

ssc/cmod_windpower.cpp, ssc/cmod_windpower_eqns.cpp
-Add error warning when power curve is 0 from failed wind power curve equations in UI. 
-See https://github.com/NREL/SAM/issues/877, https://github.com/NREL/SAM/pull/897
=> Update cmod_windpower error warnings for failed user-defined wind turbine powercurves

ssc/cmod_pvsamv1_eqns.cpp, ssc/cmod_pvsamv1_eqns.h
-Callback error for PVWatts Battery ReOpt invoke function stems from crit_load being defined even though critical load is not defined in PVWatts Battery. Added an assignment check before passing critical load to ReOpt (does not seem to be a required input)
-See https://github.com/NREL/SAM/pull/945
=> Remove crit_load input from PVWatts battery ReOpt calls

shared/lib_util.cpp
Fixes https://github.com/NREL/SAM/issues/968.
With this fix, it is clearer that the problem with the weather file (see SAM Issue 968)) is that the Day column in this weather file with one-minute data is day-of-year (1-365) instead of day-of month (1-31 for Jan, 1-28 for Feb, 1-30 for Mar, etc.).
=> Improve error messages for wfcheck

ssc/cmod_tcsmolten_salt.cpp, ssc/cmod_trough_physical.cpp, tcs/csp_solver_pc_Rankine_indirect_224.cpp, tcs/csp_solver_pc_Rankine_indirect_224.h, tcs/csp_solver_util.cpp, tcs/csp_solver_util.h
Update CSP solver component output writer to set outputs that are dependent on other variables. For example, when there are multiple sub-timesteps in a single reporting timestep, calculated the weighted average of a metric like efficiency is inaccurate. This pull requests provides a starting point for a framework that calculates efficiency on the reporting timestep interval based on the reporting timestep interval values of thermal input and power output.
=> CSP timestep reporting

tcs/csp_solver_mono_eq_methods.cpp
Addresses SAM issue: https://github.com/NREL/SAM/issues/996
The trough models assume during "off" and "startup" modes that the outlet of the trough is recirculated to the inlet, so the trough component model handles inlet/outlet temperature convergence instead of the upstream system energy balance models. The trough models occasionally crashed during freeze protection because the system convergence model was iterating on the trough inlet HTF temperature, but the trough performance model does not use input from the system model.
=> Fix freeze protection bug

shared/lib_battery_dispatch_automatic_btm.cpp, shared/lib_utility_rate.cpp, shared/lib_utility_rate.h, shared/lib_utility_rate_equations.cpp, shared/lib_utility_rate_equations.h, ssc/cmod_utilityrate5.cpp, test/input_cases/shared_rate_data.cpp, test/shared_test/lib_utility_rate_equations_test.cpp, test/shared_test/lib_utility_rate_test.cpp
Update price signals dispatch to support kWh/kW rates without crashing. The key difference here is rate_data.init_energy_rates can now be called for a single month, and peak data by TOU period is now passed into the rate calculation function for use with these rates.
=> Ssc 561 update for demand ratchets

ssc/cmod_6parsolve.cpp
This PR replaces the generic error message for cmod_6parsolve "could not solve, check inputs" with more informative error messages based on the sanity check performed on the inputs here: https://github.com/NREL/ssc/blob/5ec04426cdfc4f83c397feb7c1ef66753ab9a70e/shared/6par_solve.h#L307.
Addresses https://github.com/NREL/SAM/issues/17
To test, create a Detailed PV / No Financial case, choose the "CEC Performance Model with User Entered Specifications" option on the Module page, try different unrealistic values for the input parameters, and click **Calculate and plot**.
Alternatively, build SDKtool and try modifying parameter values in the attached LK script for SDKtool:
[coeffgen6par_sdktool.zip](https://github.com/NREL/ssc/files/8522995/coeffgen6par_sdktool.zip)
=> Improve module ceofficient generator error reporting

shared/lib_battery_dispatch_automatic_fom.cpp, shared/lib_battery_dispatch_automatic_fom.h, test/shared_test/lib_battery_dispatch_automatic_fom_test.cpp, test/ssc_test/save_as_JSON_test.cpp
Add additional variables to the FOM dispatch code such that the price to charge and discharge reflects the capacity of the battery, rather than just the maximum price in the forecast.
File for testing and comparison to HOPP:
[autodispatch_improvements_hopp.zip](https://github.com/NREL/ssc/files/8431864/autodispatch_improvements_hopp.zip)
Fixes https://github.com/NREL/ssc/issues/745
A note on save_as_JSON_test_run: the NPV in the current defaults goes up by ~2%, so it's not clear to me why this one is going down by <1%.
=> Ssc 745 improve fom dispatch

.github/workflows/ci.yml
https://github.com/NREL/ssc/runs/6181437239?check_suite_focus=true failed even though the build before it succeeded, the PR succeeded, and the build succeeds locally. It looks like some of our tests are incompatible with the latest version of gtest. Revert to the last version that worked, and fix things in an issue that is to be created.
=> pin the version of gtest to the last one that worked with our current tests

shared/lib_pv_io_manager.cpp, shared/lib_pv_io_manager.h, ssc/cmod_pvsamv1.cpp, test/ssc_test/cmod_pvsamv1_test.cpp
Apply the wiring loss and _then_ the transmission loss, so that the numbers can't be greater than 100%. Update the loss calculations so this appropriately shows up in the loss diagram. Transmission losses were added in SAM PR [1000](https://github.com/NREL/SAM/pull/1000)
I'm happy to add a unit test for this, but wanted to confirm the loss behavior with you prior to writing it.
=> 783 sequential wiring and transmission losses

shared/lib_pv_io_manager.cpp, shared/lib_pv_io_manager.h, ssc/cmod_pvsamv1.cpp, test/ssc_test/cmod_pvsamv1_test.cpp
* Apply the losses sequentially. Looks good in the time series outputs, but the losses diagram is a little off
* clean up transmission and ac wiring loss computations
* delete commented out line
* add test for fixed transmission loss behavior
* Swap the order of lifetime and availability losses so that the solls diagram percentages are computed correctly
* Add new inverter AC gross power output. Fix inverter warning with high losses
=> 783 sequential wiring and transmission losses (#790) to develop

ssc/cmod_utilityrate.cpp, ssc/cmod_utilityrate2.cpp, ssc/cmod_utilityrate3.cpp, ssc/cmod_utilityrate4.cpp, ssc/cmod_utilityrate5.cpp
Noticed that the PySAM documentation was out of date, requires fixing this definition in SSC.
=> Update module entry to reflect actual open EI compatability (version 8)

ssc/cmod_pvwattsv8.cpp
-Calculate annual AC output for availability losses applied in `adjust`
-Also see hourly outputs before adjustment factors are applied
-Fixes https://github.com/NREL/SAM/issues/987
-Example file saved in 2021.12.02 version (search 'before system availability' for annual and hourly outputs): 
[system-availability-adjust-loss-test-2020-11-29.zip](https://github.com/NREL/ssc/files/8815397/system-availability-adjust-loss-test-2020-11-29.zip)
=> Add AC outputs before adjust for pvwattsv8 (hourly and annual)

shared/lib_battery_capacity.cpp, test/ssc_test/cmod_battwatts_test.cpp
Fix issue #832 by ensuring the check_soc function is applied to both battery types.
=> add function that was enforcing dispatch soc limits for lithium ion batteries

tcs/csp_dispatch.cpp, tcs/etes_dispatch.cpp
LpSolve presolve was resulting in time periods where the reported dispatch state of charge was zero when it actually was not. This occurred at the beginning of the dispatch horizon sometimes. To fix, now dispatch solution is saved using the original model form and not the subset model after presolve. This update results in all variable values being updated.
=> Fixed dispatch reporting issue

tcs/csp_solver_pc_Rankine_indirect_224.cpp, tcs/powerblock.cpp, tcs/powerblock.h, tcs/sam_csp_util.cpp, tcs/sam_csp_util.h, tcs/sam_mw_type234.cpp
ACC model now scales with design condenser pressure. Scaling ratio is determined based on the user design inputs for condenser temperature and pressure (pressure is based on ITD input)
=> Adding ACC design scaling

ssc/common_financial.cpp
-Closes https://github.com/NREL/SAM/issues/1085
-Fix label from battery salvage value to utility escalation rate (including inflation)
-Is this output necessary?
=> Fix label for utility escalation rate

.github/workflows/ci.yml, CMakeLists.txt, test/CMakeLists.txt
* Need to verify this does not break build process for Linux and Mac
* Depends on single environment variable GTDIR pointing to top-level googletest folder as described in revised Windows build instructions: https://github.com/NREL/SAM/wiki/Windows-Build-Instructions
=> Fix issue with cmake finding debug paths for SSC tests

ssc/common_financial.cpp
-Utility escalation was being applied as 0, eliminating calculations from hourly energy and demand charges
-Closes #853
=> Fixed utility escalation rate application in BTM battery grid charging costs

ssc/cmod_etes_electric_resistance.cpp, ssc/cmod_etes_ptes.cpp, ssc/cmod_tcsmolten_salt.cpp
Add cp_system_nameplate and cp_battery_capacity to cmod outputs for downstream financial models.  Currently the these values are calculated in the user interface and then passed directly to the financial model. This is a problem when calling the model via scripts because if the technology capacity changes, these values aren't updated for the financial model.
This pull request fixes this issue for the molten salt power tower, ETES, and PTES models. This will remain an issue (along with similar issues regarding the consistency of using UI-calculated values as cmod inputs) for other technology models. @cpaulgilman @Matthew-Boyd @sjanzou
=> add cp_system_nameplate and cp_battery_capacity to cmod outputs

shared/lib_geothermal.cpp
-Closes https://github.com/NREL/SAM/issues/1156
-Allows for specifying binary plant as # of wells even though GETEM spreadsheet does not calculate total flow rate as function of # wells
=> Fix number of wells flow rate calculations for binary plants

ssc/cmod_pvsamv1.cpp
To test:
- Run a subhourly simulation
- Confirm that the AC wiring losses match the input (1% is default)
Unchecking the "save all output variables over lifetime" option is recommended if testing with a one minute weather file.
Fixes https://github.com/NREL/SAM/issues/1082
=> add ts_hour to ac wiring loss line

shared/lib_battery_dispatch.cpp, test/shared_test/lib_battery_dispatch_automatic_btm_test.cpp
Add fuel cell output power to AC outage calculations to fix https://github.com/NREL/SAM/issues/1130
File with Will's test instructions (see issue for details): 
[sam_1130_test_case.zip](https://github.com/NREL/ssc/files/9679325/sam_1130_test_case.zip)
Haven't done DC because there are no SAM configurations with batteries that are DC connected to PV with fuel cells.
=> add capability for AC connected battery to charge from fuel cell

ssc/cmod_utilityrate5.cpp, ssc/common.cpp
move en_electricity_rates to utility_rates_common, so it's assigned for retail rate dispatch.
Fixes #824. Test file available with that issue. The cases with retail rates should show reduced charging. Increasing the retail rate to $1/kWh should lead to the battery only charging once during the analysis period (when the price goes above $1100/MWh in June).
=> Fix battery dispatch for retail rate electricity purchases.

shared/lib_pv_io_manager.cpp
The monthly albedo check caused a buffer overflow from an array out-of-bounds error when spatial monthly albedos are used instead of monthly uniform albedos. The other checks are redundant to the checks on lines 185-194 in lib_pv_io_manager.cpp .
Paul, please let me know if I'm misunderstanding anything. Thanks.
=> Fix buffer overflow and remove redundant albedo checks

shared/lib_battery_dispatch_pvsmoothing_fom.cpp
Steps to get things to line up with the mainline battery SOC:
1. Open a PV-Battery FOM case
2. Use a 15 minute weather file (or shorter)
3. Set analysis period to 1 year
4. Set the ramp timestep multiplier to 1
=> Update pv smoothing battery soc at the end of the step

ssc/core.cpp
works with previous ssc test files and SDKtool with lk generated from previous releases
=> Change single number inputs to single element array inputs for SSC_ARRAY required input variables

shared/lib_battery.cpp, ssc/cmod_battery_stateful.cpp, test/ssc_test/cmod_battery_stateful_test.cpp
Fixes #918 
Problem reported here: https://sam.nrel.gov/forum/forum-general/3080-battery-augmentation-strategy.html?start=6
In that Jupyter notebook example, there are no replacements reported at the end running `simulation['Battery Replacements'].resample("Y").sum()`
Now with this fix, this cmd `simulation['Battery Replacements'].resample("Y").mean()` gives replacements at year 10 and year 19
=> add replacement for batterystateful

ssc/cmod_pvsamv1.cpp
This fixes the calculation for both gain terms and bifacial terms and this issue doesn't need to be revisited after the release.
Closes #911
=> Fix annual total loss percent output value

ssc/cmod_pvsamv1_eqns.cpp, test/ssc_test/cmod_pvsamv1_test.cpp
Use production factors from the actual system instead of lat/lon when getting size and dispatch from REopt. Additional required changes in SAM PR: https://github.com/NREL/SAM/pull/1165 Fixes #923 
Steps to test:
1. Run the attached SAM and weather files in 2021.12.02: 
[2018_weather_file_dispatch.zip](https://github.com/NREL/ssc/files/9923585/2018_weather_file_dispatch.zip)
2. Build SAM from this branch and the SAM branch sam_1092_update_reopt_script
3. See improved sizing and dispatch (via improved NPV) on branches
=> Ssc 923 use prod factors

ssc/cmod_utilityrate5.cpp, test/ssc_test/cmod_utilityrate5_test.cpp
Fixes https://github.com/NREL/SAM/issues/1273 See issue for test file. Values of bill w/o system should not change based on whether or not excess $ or kWh rollovers exist.
Establish additional variables so w/system outputs don't affect w/o system calculations. Look at the utility bill in year 2 in the test to check against these issues.
=> Fix rollover issues in bill w/o system

ssc/cmod_cashloan.cpp, ssc/cmod_communitysolar.cpp, ssc/cmod_equpartflip.cpp, ssc/cmod_host_developer.cpp, ssc/cmod_ippppa.cpp, ssc/cmod_levpartflip.cpp, ssc/cmod_merchantplant.cpp, ssc/cmod_saleleaseback.cpp, ssc/cmod_singleowner.cpp, ssc/common.cpp
Fixes #939 The fix for that is in cashloan line 1043. Test file is here, shows correct implementation of depreciation adjustments: 
[cashloan_itc_test.zip](https://github.com/NREL/ssc/files/10034373/cashloan_itc_test.zip)
I audited the other code for similar issues and didn't find any. Additional testing never hurts.
All other changes update the issue number to match https://github.com/NREL/SAM/issues/1038, so future developers aren't looking at the wrong issue.
=> Remove extraneous i==1 from cashloan. Also correct typo in comments to issue number (1038)

ssc/cmod_pvsamv1_eqns.cpp
Properly account for the fact that PVWatts only generates one year of data when calling the REopt API. Fixes https://github.com/NREL/SAM/issues/1290
Rigorous testing would include multiple timesteps and analysis periods for both PVWatts-Battery and Detailed PV-Battery
=> fix gen length issue that broke REopt sizing call

ssc/cmod_etes_electric_resistance.cpp, ssc/cmod_etes_ptes.cpp, ssc/cmod_tcsmolten_salt.cpp
MSPT, ETES, and PTES cmods calculate system capacities for capacity payments. However, the cmods were using the wrong variable name. This doesn't appear to cause problems yet, because the system nameplate is calculated in ssc equations and battery nameplate doesn't appear to be used in SSC.
=> Fix cmod output variable names

ssc/cmod_irradproc.cpp
small update to irradiance input mode 'irrad_mode', as it has option to take info from POA from reference cell or pyranometer expanding options to 0-4
@dguittet
=> Update cmod_irradproc.cpp small documentation detail

sdktool/CMakeLists.txt
Wanted to get the ssc changes for rapidJSON in wex into patch to prevent continuously merging patch into SAM_504 branch until wex and SAM are finished.
This should be the only change in ssc necessary for SAM issue 504.
=> Fix broken SDKTool with rapid json in wex/utils

.github/workflows/ci.yml
macos-11 runner seems to have some resource issues. The PVSmoothing tests are one of the most memory intensive tests. The tests run locally on Intel mac and M1 mac. macos-latest runner succeeded with push. Now testing with this pull request.
=> Changing runner to macos-latest to address pvsmoothing test failures

ssc/cmod_tcsmolten_salt.cpp
Problem: When one of the "optimize field" boxes is checked on the MSPT Solar Field page, design point calculations fail and the blue boxes display -789
Background: The MSPT model defines all calculated values by calling the cmod in “design point mode”, designated by cmod input sim_type = 2. The point of the checkboxes is to run the layout routines during the annual simulation, not before (otherwise, the user would just click the macro options). However, that means that the design point that the model will calculate at the beginning of the annual simulation doesn’t exist yet. In the current code, the cmod design-point routine will skip the heliostat field layout, which results in a crash downstream because subsequent design point calculations want these values defined.
Solution:
I think …
=> MSPT design point w/ field layout design selected

shared/lib_pv_io_manager.cpp
-Set clearance height for Sandia module model to use with rear irradiance calculations (no bifacial calculations)
-Fixes https://github.com/NREL/SAM/issues/1296
=> Sandia clearance height

ssc/cmod_utilityrate5.cpp
-Requirement check in utilityrate5.cpp output variable not working
-Using system_use_lifetime_output check in utilityrate5 instead
-'Lifetime load' doesn't make sense for non-lifetime projects, so removing variable rather than using it for single year outputs
Fixes https://github.com/NREL/ssc/issues/947
=> Remove unused lifetime load output for non-lifetime projects

shared/lib_battery_powerflow.cpp
Fixes https://github.com/NREL/SAM/issues/1324
The specific combination of factors in the test file was driving batt_to_load_ac negative, which lead to a positive batt_to_grid_ac, which caused an infinite loop between the powerflow code and the dispatch code. Fix this by preventing these variables from going negative.
=> Ensure key variables in the powerflow code have a minimum of zero

ssc/cmod_battery.cpp
Fixes https://github.com/NREL/ssc/issues/948
Test file: 
[losses_test_case.zip](https://github.com/NREL/ssc/files/10513514/losses_test_case.zip)
=> add exec errors to prevent simulations from running with negative system losses for batteries

ssc/cmod_geothermal.cpp
-Update var table for max resource temperature in SDK
-Captured in UI with https://github.com/NREL/SAM/pull/1341
-Max temperature of 373
-Fixes https://github.com/NREL/SAM/issues/1340
=> Add max constraint to geothermal resource temperature

ssc/cmod_swh.cpp
Fixes the collector loop solar water heating mass flow as this is not currently dependent on the number of collectors, with the value currently being a constant sized for two collectors.
@cpaulgilman Can you please make sure I'm not misunderstanding what is going on here? I think the UI originally sized this parameter but no longer does.
Closes #1003
=> Size the collector loop mass flow based on n_collectors

shared/lib_weatherfile.cpp, shared/lib_weatherfile.h, ssc/cmod_wfcheck.cpp, ssc/cmod_wfcsv.cpp
- Allow files that have minimum required metadata, regardless of number of columns in metadata header rows.
- Add Version to list of metadata columns to support NSRDB version numbers.
- Test with files from NSRDB, PVWatts API, and hand-edited to have different metadata row lengths.
Fixes #937
Weather files for testing on Solar Resource  input page with any solar tech in SAM UI: Should add all of these files to solar resource library and run a simulation, except WIND Toolkit file, which should be ignored: [ssc-937-test-weather-files.zip](https://github.com/NREL/ssc/files/11326254/ssc-937-test-weather-files.zip)
Update SAM CSV for Solar Help topic to add version to table of accepted metadata items. (Done in local branch for Patch 2 release in separate PR.)
=> Allow more flexible SAM CSV for solar weather file format

shared/lib_battery_voltage.cpp, test/shared_test/lib_battery_voltage_test.h
Fixes https://github.com/NREL/ssc/issues/1007
Testing with the case in the issue should produce an error message, testing with the defaults should not.
=> Throw an error if duplicate entries in the voltage table produce zero slope

nlopt/timer.c
"Call to undeclared function 'gettimeofday'; ISO C99 and later do not support implicit function declarations" compile error
=> Fixes MacOS compile error

ssc/cmod_battery.cpp, ssc/cmod_pvsamv1.cpp
Add checks for critical load length as compared to load length. Fixes https://github.com/NREL/ssc/issues/1015 - SAM branch [load_ui_checks](https://github.com/NREL/SAM/tree/load_ui_checks) required to test. (pull request forthcoming)
Test should get error messages in the file in the issue.
=> Add errors for length mismatch between critical load and electric load

shared/lib_util.cpp, shared/lib_util.h, ssc/common.cpp, test/ssc_test/cmod_pvsamv1_test.cpp
-Daily mode of adjustment factor widget was returning 0-6 for Monday-Sunday rather than 0-364
-Change function to correct indexing for adjustment factor
=> Fix adjustment factor daily timeseries option

shared/lib_battery_dispatch_automatic_btm.cpp, shared/lib_battery_dispatch_automatic_btm.h, ssc/cmod_battery.cpp, test/shared_test/lib_battery_dispatch_automatic_btm_test.cpp, test/ssc_test/cmod_battery_pvsamv1_test.cpp
Provides the same information to price signals dispatch as peak shaving has available at each step: assumes the battery can read current PV and load to make dispatch decisions
NPV of current patch code for forecast case: $8,484,012
NPV of this code: $8,731,707
File to test with: 
[price_signals_forecast_diff.zip](https://github.com/NREL/ssc/files/11578280/price_signals_forecast_diff.zip)
=> Give price signals dispatch info about real time system power and load for dispatch for apples to apples comparison of forecast error

tcs/csp_solver_trough_collector_receiver.cpp, tcs/csp_solver_trough_collector_receiver.h
Fix issue #1441 [https://github.com/NREL/SAM/issues/1441](url) 
Add reflective losses to receiver incident thermal power
=> Add absorber reflected radiation to heat loss output in evacreceiver

ssc/cmod_tcsmolten_salt.cpp
Add default pumping power of 2% if not reported from receiver design method
=> Fix MSPT cavity receiver system capacity calculation

ssc/cmod_cashloan.cpp, ssc/common.cpp
Fixes #644
Remove cf_ptc_total from cashloan and common. 
Ignoring legacy cmod_ippppa.
=> Remove total PTC output from all models

shared/lib_cec6par.cpp, ssc/cmod_pvsamv1.cpp
-Throw error in pvsamv1 when ambient pressure and dew point (or wet bulb) is missing from the weather file
-Make tcell nan when this happens to make sure calculation does not continue as normal
-Fixes https://github.com/NREL/sam/issues/1428
=> Helpful error messages when cell temperature heat transfer method is missing data

ssc/cmod_hcpv.cpp, ssc/cmod_windpower.cpp, ssc/common.cpp, test/input_cases/pvsamv1_battery_common_data.h, test/ssc_test/cmod_pvsamv1_test.cpp
This PR fixes the setup of availability losses to properly determine the loss timestep. It updates the error messages to give more helpful information (and fixes a mislabeled error message in hcpv). It also updates the battery tests for these losses, which had the loss enabled when it wasn't being used. Fixes #181 . This does need one UI update to the widget in the wind model in the SAM repo, which I will wait until @cpaulgilman is finished doing his UI review to complete.
=> Fixes to availability losses

ssc/cmod_fresnel_physical_iph.cpp
Fix issue #1081 [https://github.com/NREL/ssc/issues/1081](url)
Fix Installed cost per capacity calculation caused by unit conversion error.
=> Fix MSLF IPH Installed cost per capacity calculation error  

ssc/cmod_utilityrate5.cpp
Fixes #785 
Add grid_outage as an optional input to utility_rate 5. When there is a grid outage, set grid use to zero. While cmod_grid handled this effectively for the load, these additional changes are required to preserve the data in gen while not accumulating net metering credits during an outage.
To test:
1. Open a PV+Battery behind the meter case
2. Set up a full year grid outage (file with 8760 ones for testing) with any critical load percentage: 
[_8760_ones.csv](https://github.com/NREL/ssc/files/13491312/_8760_ones.csv)
3. Run the case
4. Hourly to/from grid variables should be zero, net metering credits should not be earned.
Testing other compensation methods would be good rigor.
=> Fix SSC 785 hourly variables

ssc/cmod_utilityrate5_eqns.cpp, ssc/ssc_equations.h
Fixes https://github.com/NREL/SAM/issues/1621
Goes with https://github.com/NREL/SAM/pull/1641
Improve error message when SAM `net_metering` option is not available in URDB `dgrules` so that UI callback error in SAM makes more sense.
Rename URDB V7 to V8 in labels.
=> Improve REopt error messages for invalid dgrules values

ssc/cmod_hybrid.cpp
Note filtering to SSC_WARNING and SSC_ERROR only. SSC_NOTICE includes several messages that are not useful on simulation results dialog for test file (PVWatts tilt = 95) :
[ssc_1105.zip](https://github.com/NREL/ssc/files/13598044/ssc_1105.zip)
-------------------------------------------------------------------
compute fail(hybrid): pvwattsv8 execution error.
fail(tilt, max=90): 95
E=90,S=180,W=270
total system losses
0=false,1=true
0=shadingdb,1=average,2=maximum,3=minimum
0=false,1=true
0=false,1=true
0=false,1=true
0=false,1=true
'adjust' and 'constant' separated by _ instead of : after SAM 2022.12.21
'adjust' and 'en_timeindex' separated by _ instead of : after SAM 2022.12.21
'adjust' and 'en_periods' separated by _ instead of : after SAM 2022.12.21
Simulation Hybrid failed :Simulation …
=> Add ssc_module_exec_with_error per @dguittet with filtering to fix #1105

ssc/cmod_battery.cpp
Fixes #1110, see issue for test instructions.
Due to the differences in battery dispatch, the grid outage case has 2 more steps where the system meets load than the non outage version.
Still open to discussing whether this is on-time for the release or should wait for patch one, hence the lack of milestone tag.
=> Add check for crit load unmet to self consumption metrics

shared/lib_battery_dispatch_manual.cpp
Fix #1112, see issue for test instructions. Expect the two SAM cases in that file to match their dispatch output.
No milestone since it's not clear whether this will land in the release or patch 1 - for discussion at today's meeting.
=> Correct size versus iprofile index for manual dispatch

shared/lib_irradproc.cpp, shared/lib_irradproc.h
-Individual components of bifacial rear irradiance gain in PV loss diagram were reporting wrong values due to clear sky calls of function calculating rear irradiance being made after original call. 
-Update variable declarations to not overwrite bifacial irradiance outputs
-No changes to bifacial energy calculations, only loss diagram outputs
=> Fix reporting of ground reflected rear irradiance gains in loss diagram

ssc/cmod_pvsamv1.cpp
-Fixes #1123 
-Fixes https://github.com/NREL/SAM/issues/1685
-Check for nan for weather file DNI, use calculated DNI as alternative
=> Use calculated DNI for Allen method when there is no DNI in weather file

shared/lib_battery_powerflow.cpp, shared/lib_battery_powerflow.h, ssc/cmod_utilityrate5.cpp, ssc/common_financial.cpp, test/ssc_test/cmod_battery_pvsamv1_test.cpp
- Use same tolerance in powerflow code and utility rate code, which both generate "electricity from grid to x varaibles"
- Rename gen_purchases so it's clear that it does not include load it btm models
Fixes https://github.com/NREL/SAM/issues/1684, see the issue for test file.
=> Address confusion and consistency in powerflow variables

shared/lib_pvshade.cpp
-Fixes #1122 
-Outlier values seem to be due to high gcr + high tilt angle, don't see a use case where value should ever be greater than 1.0
=> Set upper limit of one for diffuse sky shading non-linear factor

shared/lib_weatherfile.cpp
Handle NSRDB weather files with both Local Time Zone and Time Zone in header where one has valid value and the other is empty.
Goes with https://github.com/NREL/SAM/pull/1720
=> Time zone fix for NSRDB MSG V1.0.0

shared/lib_utility_rate_equations.cpp, test/shared_test/lib_battery_dispatch_automatic_btm_test.cpp
The TOU demand function changed in https://github.com/NREL/ssc/pull/1135/files expects the year 1 index. Correct this, and add a test that reproduces the issue by setting up a multi-year rate forecast object.
=> Modify index to year 1 index to correctly utilize tou demand function

ssc/vartab.h
=> Clear var_data before copy

ssc/common.cpp, ssc/core.cpp
To test:
1. pull SAM_1733 branch of ssc and patch branches of other repos and build
2. create PVWatts/Commercial case
3. Financial parameters page - set straight line depreciation years to 0
4. select straight line depreciation and run - error as expected
5. select different depreciation method and run - no error as expected.
See https://github.com/NREL/SAM/issues/1733 for simulation error in current release.
=> Address SAM issue #1733 while keeping functionality of SAM issue #1184

shared/lib_battery.cpp, shared/lib_battery_capacity.cpp, shared/lib_battery_dispatch.cpp, shared/lib_battery_dispatch_manual.cpp, shared/lib_resilience.cpp, test/ssc_test/cmod_battery_pvsamv1_test.cpp, test/ssc_test/cmod_battery_test.cpp
Consistently use the powerflow tolerance throughout the battery issue to mitigate issues caused by inconsistent tolerances. Results of the parametric run after changes:
See https://github.com/NREL/SAM/issues/1806 for test file. See https://github.com/NREL/ssc/pull/1132 for history on powerflow tolerance.
Test changes for grid outage and resilience code were required to accommodate tighter tolerances. Reported resilience metrics have decreased due to changing tolerance from 2 W to 0.005 W.
=> Sam 1806 make tolerances more consistent

shared/lib_pv_io_manager.cpp
Fixes https://github.com/NREL/ssc/issues/1190
Should be good to go if SSC tests pass
=> Initialize ground clearance height for IEC module model

shared/lib_battery_dispatch.cpp, shared/lib_battery_dispatch.h, ssc/cmod_battery.cpp, ssc/cmod_battery.h
-Adds year 1 energy charged from system, grid metrics to report in standalone battery metrics table
-See (https://github.com/NREL/SAM/issues/1589)
=> Standalone battery  metrics

ssc/cmod_biomass.cpp, ssc/cmod_etes_electric_resistance.cpp, ssc/cmod_etes_ptes.cpp, ssc/cmod_fresnel_physical.cpp, ssc/cmod_fresnel_physical_iph.cpp, ssc/cmod_generic_system.cpp, ssc/cmod_geothermal.cpp, ssc/cmod_hcpv.cpp, ssc/cmod_linear_fresnel_dsg_iph.cpp, ssc/cmod_mhk_tidal.cpp, ssc/cmod_mhk_wave.cpp, ssc/cmod_mspt_iph.cpp, ssc/cmod_pvsamv1.cpp, ssc/cmod_pvwattsv5.cpp, ssc/cmod_pvwattsv7.cpp, ssc/cmod_pvwattsv8.cpp, ssc/cmod_swh.cpp, ssc/cmod_tcsdish.cpp, ssc/cmod_tcsgeneric_solar.cpp, ssc/cmod_tcslinear_fresnel.cpp, ssc/cmod_tcsmolten_salt.cpp, ssc/cmod_tcsmslf.cpp, ssc/cmod_tcstrough_empirical.cpp, ssc/cmod_tcstrough_physical.cpp, ssc/cmod_trough_physical.cpp, ssc/cmod_trough_physical_iph.cpp, ssc/cmod_windpower.cpp, ssc/common.cpp, ssc/common.h
Refactor adjust losses to make them more accessible to the battery. We expect no changes, but need to test to make sure this approach is threadsafe. My initial runs with parameterics looked reasonable.
=> Refactor adjust losses to use vartable instead of cmod 

shared/lib_utility_rate_equations.cpp
The tier tolerances code (from https://github.com/NREL/ssc/pull/1207) didn't work well with large numbers other than 1e+38. Improve handling of floating point tolerances in that code.
To test: 
[rates-1e14-max.zip](https://github.com/user-attachments/files/17667454/rates-1e14-max.zip)
should run.
=> Better handling of floating point numbers for tier tolerences

shared/lib_battery_lifetime_calendar_cycle.cpp, shared/lib_battery_lifetime_calendar_cycle.h, test/shared_test/lib_battery_capacity_test.h, test/shared_test/lib_battery_test.cpp, test/shared_test/lib_battery_test.h, test/ssc_test/cmod_battery_pvsamv1_test.cpp, test/ssc_test/cmod_battery_test.cpp
I modified the cycle calendar model to take the sum instead of the min. Here are the results of 25-yr battery capacity percent (replacements are off) across the different chemistries and models. Overall, there are 6675 cycles. Average DOD is ~50%
The table models have more degradation now.
However, whereas in the Old column, the NMC/Gr table and algebraic model both had more degradation than LFP, in the New version, the LFP table has less degradation than NMC/Gr Alg. The LMO/LTO table doesn’t change because the calendar loss is 0.
This is fine because the calendar-cycle models aren’t comparable to the algebraic ones—apples and oranges.
Model | Value | Old | New
-- | -- | -- | --
NMC/Gr Alg | 25-yr cap % | 76.0021 | 76.0021
NMC/Gr Table | 25-yr cap % | 65.4057 | 47.6304
LFP/Gr Table | …
=> Battery cycle-calendar life model updated to use sum not min

ssc/cmod_singleowner_heat.cpp
Fixes missing value for PPA price in cents/MMBtu for analysis period year - see https://github.com/NREL/SAM/issues/1927
=> Fix SAM issue 1927

ssc/cmod_fresnel_physical_iph.cpp
The MSLF IPH model calculation of aux_design and bop_design was incorrect, because it was using the electric capacity (zero), rather than thermal capacity. The code has been updated to follow the same logic as the Trough IPH model.
=> Fix MSLF IPH bug calculating aux and bop

ssc/cmod_fresnel_physical_iph.cpp, ssc/cmod_mspt_iph.cpp, ssc/cmod_trough_physical_iph.cpp
Added placeholder variables to tower, trough, and mslf IPH cmods for use by future physical heat sink model.
=> Add placeholder variables for IPH physical heat sink model

ssc/common.cpp
-Allows AC monthly energy to not be labeled as AC for IPH models
-Still shows AC monthly energy for hybrid configs
=> Update hybrid om vartable to input monthly_energy, not inout

ssc/cmod_fresnel_physical.cpp, ssc/cmod_hybrid.cpp, ssc/cmod_pvsamv1.cpp, ssc/cmod_pvwattsv8.cpp, ssc/cmod_trough_physical.cpp, ssc/common.cpp, test/ssc_test/cmod_hybrid_test.cpp
Add system_capacity_ac outputs to PVSAMV1 and PVWattsV8 to have consistent variables to work with in the hybrids module
Use ac nameplate capacity in the hybrids module for consistency with other models.
Fixes #1259 
Can merge into other hybrids branch, or can merge into develop after that one goes first.
=> Ssc 1259 scale w pv ac

ssc/cmod_utilityrate5.cpp, ssc/sscapi.cpp, test/ssc_test/cmod_utilityrate5_test.cpp
Use a boolean instead of tier_charge == 0 to determine whether time series rates or table rates should be used.
Fixes https://github.com/NREL/SAM/issues/1964
=> Allow for zero time series buy and sell rates

shared/lib_battery_capacity.cpp, test/shared_test/lib_battery_dispatch_automatic_btm_test.cpp, test/shared_test/lib_battery_dispatch_manual_test.cpp, test/ssc_test/cmod_battery_pvsamv1_test.cpp, test/ssc_test/cmod_hybrid_test.cpp
The check_SOC() function in capacity_t was written before the grid outage code, and didn't expect the SOC limits to change dynamically during the simulation. Therefore at the end of the grid outage, the check_SOC() function granted the battery some free energy.
Changing the function means that the charge value is only adjusted when the current is adjusted, and the battery doesn't spontaneously gain energy without charging.
Test file here: [ssc_1270_test_case (2).zip](https://github.com/user-attachments/files/18828139/ssc_1270_test_case.2.zip)
Expectation is that the grid outage will end a few hours before the battery recharges above 10% (even though the minimum SOC is 30%.
Fixes #1270
=> Avoid giving free energy at the end of a grid outage

shared/lib_battery_powerflow.cpp
The previous grid limits code did not properly account for inverter night time losses, this code corrects that issue.
Note that there are still some issues with power to grid below 10% battery SOC. Those might be better solved as a part of https://github.com/NREL/ssc/issues/1202
Fixes https://github.com/NREL/SAM/issues/1982
=> Incorperate inverter losses into grid limits code

ssc/cmod_windpower.cpp, ssc/common.cpp
Fix #1283
To test, run a default Wind / No Financial case with and without time series adjustment factors. The difference between the two runs should be the adjustment factor applied once, not twice as reported in #1283.
The adjustment factors should work correctly for the following combinations:
* Hourly weather file with hourly losses
* Subhourly weather file with subhourly losses
* Weibull distribution with hourly losses
* Wind resource probability table with hourly losses
* Constant loss wake model option with hourly or subhourly simulations/losses
A simulation error should be generated with the wrong combination of wind data time step and loss time step.
The attached file has .sam file with cases set up for these tests and a 15-minute wind file: …
=> Fix wind adjustment factor double-counting

.github/workflows/ci.yml, test/compare_elapsed_time.py
Add step in existing GitHub workflow to upload an artifact containing CSVs of elapsed test times
In a future branch, will add a new Workflow to compare CSVs across branches. Need to merge this one first so other branches upload the artifacts
=> Add Github Action to Export Test Times

ssc/cmod_communitysolar.cpp
To test, run the attached PVWatts / Community Solar SAM project file with and without subscriber upfront fees and check cashflow subscriber benefits and subscriber NPV values in results metric tables
[SAM_1867.zip](https://github.com/user-attachments/files/19179956/SAM_1867.zip)
=> Update cmod_communitysolar to address https://github.com/NREL/SAM/issues/1867

shared/lib_utility_rate_equations.cpp, shared/lib_utility_rate_equations.h, ssc/cmod_utilityrate5.cpp, test/ssc_test/cmod_utilityrate5_test.cpp
Fixes https://github.com/NREL/SAM/issues/1985
To test:
1. Create a PVWatts commercial case
2. Enable billing demand lookback
3. Run the case - case should run successfully
4. Set all "Included in billing demand" values under "billing demand by time-of-use period for demand charges" values to zero
5. Run the case - new error message should appear.
=> Throw an error if all billing demand periods are zero

shared/lib_battery_dispatch.h, shared/lib_battery_dispatch_manual.cpp, shared/lib_battery_dispatch_manual.h, ssc/cmod_battery.cpp, ssc/cmod_battery.h
New variable "Battery manual dispatch period in this timestep" should appear for manual dispatch (both front of meter and behind the meter) but not for other dispatch modes.
Chose to do a lifetime variable instead of year 1 since I think we're trying to move in that direction.
Fixes https://github.com/NREL/ssc/issues/1230
=> Add new dispatch period output for manual dispatch

ssc/cmod_utilityrate5.cpp
Addressed SAM issue https://github.com/NREL/SAM/issues/1834
Throws error message rather than producing erroneous results.
To test follow the steps:
Load a behind the meter model
Set the compensation for distributed generation to net billing
Set a maximum tier to 100 kWh (or something lower than the month's usage
Run simulation
The bill savings are negative
The following file can be used to test a valid case and a case with an invalid maximum usage for the maximum tier.
[SAM_1834.zip](https://github.com/user-attachments/files/19483818/SAM_1834.zip)
=> Throw error whenever cumulative energy exceeds maximum tier usage for a given period.
