NREL/ssc

shared/lib_geothermal.cpp
ssc/cmod_sco2_design_point.cpp

Reorder private  class members to suppress G++ -Wreorder warnings.

---

build_linux/Makefile-tcs
tcs/cavity_calcs.cpp
tcs/csp_dispatch.cpp
tcs/csp_solver_core.cpp
tcs/csp_solver_mspt_receiver_222.cpp
tcs/direct_steam_receivers.cpp
tcs/heat_exchangers.cpp
tcs/sam_lf_st_pt_type232.cpp
tcs/sam_mw_lf_type261_steam.cpp
tcs/sam_sco2_recomp_type424.cpp
tcs/sco2_pc_core.cpp
tcs/sco2_pc_core.h
tcs/sco2_pc_csp_int.cpp
tcs/tcskernel.cpp

An ad-hoc set of fixes for g++ warnings. Sending them in batches!

Fix more warnings in the tcs directory

---

solarpilot/AutoPilot_API.cpp
solarpilot/AutoPilot_API.h
solarpilot/Financial.cpp
solarpilot/Flux.cpp
solarpilot/Heliostat.cpp
solarpilot/OpticalMesh.cpp
solarpilot/Receiver.cpp
solarpilot/Receiver.h
solarpilot/SolarField.cpp
solarpilot/Toolbox.cpp
solarpilot/interop.cpp
tcs/csp_solver_core.cpp

... and adding conditions for displaying start and stop times as warnings in MSPT module. 
This fix partially addresses pull request #38.

resolving compiler warnings due to unused variables in solarpilot

---

tcs/csp_solver_trough_collector_receiver.cpp
tcs/csp_solver_trough_collector_receiver.h
tcs/interpolation_routines.cpp
tcs/powerblock.cpp
tcs/sam_mw_trough_type250.cpp

The patch fixes a bunch of signed and unsigned comparison warnings.

More tcs dir fixes

---

build_vs2013/ssc_vs2013.vcxproj
build_vs2017/ssc_vs2017.vcxproj

Update library names and build events to streamline workflow

Ssc project file

---

ssc/cmod_battery.cpp
ssc/cmod_belpe.cpp
ssc/cmod_biomass.cpp
ssc/cmod_lcoefcr.cpp
ssc/cmod_poacalib.cpp
ssc/cmod_pv_get_shade_loss_mpp.cpp
ssc/cmod_pvsamv1.cpp
ssc/cmod_pvwattsv0.cpp
ssc/cmod_sco2_csp_system.cpp
ssc/cmod_sco2_design_point.cpp
ssc/cmod_singleowner.cpp
ssc/cmod_solarpilot.cpp
ssc/cmod_swh.cpp
ssc/cmod_tcsiscc.cpp
ssc/cmod_tcsmolten_salt.cpp
ssc/cmod_utilityrate2.cpp
ssc/cmod_utilityrate3.cpp
ssc/cmod_utilityrate4.cpp
ssc/cmod_utilityrate5.cpp
ssc/cmod_wfcsv.cpp
ssc/cmod_windpower.cpp
tcs/sam_csp_util.h

Only a handful of warnings now remain.

Fixes for the ssc directory

---

solarpilot/OpticalMesh.cpp
tcs/csp_solver_pt_heliostatfield.cpp
tcs/csp_solver_pt_sf_perf_interp.cpp
tcs/sam_pf_dish_parasitic_type298.cpp
tcs/storage_hx.cpp

Fix 'assigning field to itself' warnings from clang

---

shared/lib_cec6par.cpp
shared/lib_geothermal.cpp
shared/lib_pv_shade_loss_mpp.cpp
shared/lib_weatherfile.cpp
shared/lib_weatherfile.h
shared/lib_wind_obos.cpp
shared/lib_windwakemodel.cpp

This fixes all warnings found by clang.

Fix all remaining warnings in the shared directory

---

shared/lib_weatherfile.cpp

This should be fairly obvious from inspection. Thanks!

Rewrite cmp_ext to use C++ strings

---

solarpilot/SolarField.cpp
solarpilot/SolarField.h
solarpilot/interop.cpp

Fixes #145. Tested with no effect on SSC. Required for SolarPILOT standalone.

Support storing/saving heliostat enabled and in-layout state

---

tcs/sam_mw_trough_type250.cpp

Fix header sizing calculation

---

tcs/sam_mw_trough_type250.cpp

Fix interconnect internal energy calculation

---

tcs/sam_mw_trough_type250.cpp

Fix runner pressure drop calculation

---

tcs/sam_mw_trough_type250.cpp

Fix htf volume calc to-from sgs and normalize first runner length

---

tcs/sam_mw_trough_type251.cpp

Fixes #178. See issue for documentation.

Physical trough operations

---

solarpilot/interop.cpp
solarpilot/interop.h

To include weighted average value. Fixes #184.

Updating heliostat field-wide loss calculations 

---

ssc/cmod_tcsmolten_salt.cpp
tcs/csp_dispatch.cpp
tcs/csp_dispatch.h
tcs/csp_solver_core.cpp
tcs/csp_solver_core.h

csp_consolidate is the current development branch for the O&M optimization project.

Merging changes for AMPL back into the csp_consolidate branch 

---

build_vs2017/test.vcxproj.filters

@Matthew-Boyd can you confirm this pull request for the one commit I'm pushing up?

Re-organized test folder for ssc_vs2017 solution

---

ssc/cmod_equpartflip.cpp
ssc/cmod_levpartflip.cpp
ssc/cmod_saleleaseback.cpp
ssc/cmod_singleowner.cpp

Clean up PPA financial model variable labels for send-to-Excel with equations

PPA output names cleanup

---

shared/lib_iec61853.cpp

I found a handful of errors/typos in the iec61853 moduel model that were significantly affecting results and corrected them. I also changed the IAM model to consider sky and ground diffuse effects using the same approach as the cec and mlm models.

Fix: iec61853 module model errors

---

ssc/cmod_utilityrate5_eqns.cpp
test/ssc_test/cmod_utilityrate5_test.cpp

fix reopt sizing button error:
- bug fix in ElectricityRatesToURDBv7 conversion function

fix urdb equation conversions to flatdemandmonths & flatdemandstructure

---

test/shared_test/lib_time_test.cpp
test/ssc_test/cmod_battery_pvsamv1_test.cpp
test/ssc_test/cmod_windpower_test.cpp

Correct the logic to bypass the test

fix landbosse test bypass issue

---

ssc/cmod_tcsmolten_salt.cpp
tcs/csp_solver_core.cpp
tcs/csp_solver_mspt_collector_receiver.cpp
tcs/csp_solver_mspt_collector_receiver.h
tcs/csp_solver_mspt_receiver.cpp
tcs/csp_solver_mspt_receiver.h
tcs/csp_solver_mspt_receiver_222.cpp
tcs/csp_solver_mspt_receiver_222.h
tcs/csp_solver_pt_receiver.cpp
tcs/csp_solver_pt_receiver.h

commit 5c17a1df0a740bb347ccbcfb05052978ae96ca92
Merge: 22da216a af539695
Author: Matthew Boyd <mr.matthew.boyd@gmail.com>
Date:   Fri May 15 09:36:29 2020 -0600
Merge branch 'develop' into csp_mspt_receiver_flow_control
commit 22da216a0eead4ac2b761963a33d65ddf36050a3
Author: Matthew Boyd <mr.matthew.boyd@gmail.com>
Date:   Fri May 15 09:28:04 2020 -0600
Fix charge estimating bug
commit 270201e01a33941ceb0f0b3dc264a3a314629e39
Merge: 16db92bc 04c7253e
Author: Matthew Boyd <mr.matthew.boyd@gmail.com>
Date:   Fri May 15 09:19:03 2020 -0600
Merge branch 'develop' into csp_mspt_receiver_flow_control
commit 16db92bccf9d02496c3010ffaa2c107d637b372b
Merge: 0d5b1a90 f4490f03
Author: Matthew Boyd <mr.matthew.boyd@gmail.com>
Date:   Thu May 14 15:44:57 2020 -0600
Merge branch 'develop' into …

Clear-sky power tower plant control including transient receiver (squashed)

---

ssc/cmod_pvwattsv7.cpp

Revert "Comments for pysam"

---

ssc/cmod_battery.cpp

https://github.com/NREL/SAM/pull/317

replace batt length, width & height with surface_area

---

ssc/cmod_utilityrate5.cpp

Solves SAM issue https://github.com/NREL/SAM/issues/320
Note that this will change the subhourly test results in https://github.com/NREL/ssc/pull/377 once it is merged in.

Fix hardcoded index in net metering calculation

---

ssc/cmod_utilityrate5.cpp

Update and create separate enable and validations for time step buy rates

Explicitly address SAM issue 343

---

shared/lib_battery_powerflow.cpp
shared/lib_battery_voltage.cpp
test/shared_test/lib_battery_voltage_test.cpp
test/shared_test/lib_battery_voltage_test.h

Same changes as #425, plus two tests for lib_battery_voltage

Ssc 412 into develop

---

shared/lib_battery.cpp
shared/lib_battery_dispatch.cpp
shared/lib_battery_powerflow.cpp

All efficiencies for https://github.com/NREL/ssc/issues/412 are now between 89% and 91%. A number of fixes from develop were needed, as well as an update to the starting assumption for DOD_best in case the projected SOC lies outside of the voltage table.
To test: run https://sam.nrel.gov/media/kunena/attachments/101439/VRF_2020-06-19.sam and check that the annual charged energy is greater than the annual discharged energy in all cases.
After this gets merged into patch, I'll setup a separate PR for merging into develop, since a lot of files have moved and many of these changes are already there.

Fix round trip efficiency issues for voltage table.

---

shared/lib_time.cpp
ssc/cmod_battery.cpp
ssc/cmod_pvsamv1.cpp
test/ssc_test/cmod_pvsamv1_test.cpp

Add check for dt_hour > 1 and step_per_hour == 0

---

shared/lib_util.cpp

Fix new G++ sign comparison warning

---

shared/lib_weatherfile.cpp

Update https://github.com/NREL/ssc/pull/448 based on feedback.

re-use existing adjustment from 1-24 to 0-23

---

test/ssc_test/cmod_windpower_test.cpp

Update test results
@parangat94

update LandBOSSE to v2.3.0.3

---

shared/lib_irradproc.cpp

initialize irrad_proc with defaults for optional inputs & check for NaN

---

ssc/cmod_utilityrate5.cpp
ssc/core.cpp
ssc/core.h

Add unassign to compute_module class and unassign demand charges per period outputs when demand charges are not enabled.

Fixes SAM issue #442

---

CMakeLists.txt

Changing cmake to 3.10

---

ssc/cmod_battery.cpp
test/input_cases/battery_common_data.h

Update batt_cycle_cost to only be required when batt_cycle_cost_choice==1
Tested by removing batt_cycle_cost from the setup of CMBattery_cmod_battery

496 update required vars

---

ssc/cmod_battery.cpp

-Adds error message for impossible voltage model Vfull, Vexp, or Vnom inputs
-Closes #517

Added error message for bad voltage model inputs

---

shared/lib_battery.cpp
shared/lib_battery.h
shared/lib_battery_lifetime.cpp
shared/lib_battery_lifetime.h
shared/logger.cpp
ssc/cmod_battery_stateful.cpp
ssc/cmod_battery_stateful.h
test/shared_test/lib_battery_test.cpp
test/ssc_test/cmod_battery_stateful_test.cpp

Add ChangeTimestep function to `battery_t`
Rename all `dt_hour` vars to `dt_hr`
Close #523

Adaptive battery timesteps

---

ssc/common.cpp

Fixed units on Battery replacement cost Data series

---

ssc/cmod_mhk_costs.cpp
ssc/cmod_mhk_tidal.cpp
ssc/cmod_mhk_wave.cpp

-Fixed compiler errors in mhk computer modules

Mhk compiler errors

---

ssc/cmod_tcsgeneric_solar.cpp

fix Tcsgeneric_solar with "global" as gh input

---

ssc/cmod_battery.cpp
ssc/cmod_battwatts.cpp
ssc/cmod_biomass.cpp
ssc/cmod_fuelcell.cpp
ssc/cmod_generic_system.cpp
ssc/cmod_geothermal.cpp
ssc/cmod_hcpv.cpp
ssc/cmod_linear_fresnel_dsg_iph.cpp
ssc/cmod_pvsamv1.cpp
ssc/cmod_pvwattsv7.cpp
ssc/cmod_swh.cpp
ssc/cmod_tcsdirect_steam.cpp
ssc/cmod_tcsdish.cpp
ssc/cmod_tcsgeneric_solar.cpp
ssc/cmod_tcsiscc.cpp
ssc/cmod_tcslinear_fresnel.cpp
ssc/cmod_tcsmolten_salt.cpp
ssc/cmod_tcsmslf.cpp
ssc/cmod_tcstrough_empirical.cpp
ssc/cmod_tcstrough_physical.cpp
ssc/cmod_trough_physical.cpp
ssc/cmod_trough_physical_iph.cpp
ssc/cmod_windpower.cpp
ssc/common.cpp
ssc/common.h

-Added function to common that stores 365 days x 24 hour System power generated data in matrix
-Used for contour plotting on summary page

Contour plots of system power generated for summary page

---

ssc/common.cpp

-Fix calculation of day of year that timestep fits into based on number of timesteps within each hour
-Remove unused code

Make heatmap of system power generated dynamic to time interval of weather file

---

test/shared_test/csp_solver_core_test.cpp

Fix on all platforms - replaces approved pull request 649 which did not work on Travis

Cent os7 regex replace removal

---

ssc/cmod_cashloan.cpp
ssc/cmod_communitysolar.cpp
ssc/cmod_equpartflip.cpp
ssc/cmod_host_developer.cpp
ssc/cmod_levpartflip.cpp
ssc/cmod_merchantplant.cpp
ssc/cmod_saleleaseback.cpp
ssc/cmod_singleowner.cpp

I found an index out of bounds error caused by the changes in https://github.com/NREL/ssc/pull/641
This fixes the issue across the financial models.

update index that was missed in PR 641

---

shared/lib_aoi.h
shared/lib_pv_incidence_modifier.cpp
shared/lib_pv_incidence_modifier.h
shared/lib_wind_obos_cable_vessel.cpp
shared/lib_wind_obos_cable_vessel.h
ssc/cmod_iph_linear_fresnel_dsg.cpp
ssc/cmod_sco2_offdesign.cpp
ssc/cmod_sp_ty.cpp
ssc/cmod_tcslinear_fresnel_dsg_csp_solver.cpp
ssc/cmod_tcsmolten_salt_tcs_solver.cpp
ssc/cmod_test_ud_power_cycle.cpp
test/input_cases/mhk/mhk_tidal_inputs.h
test/input_cases/mhk/mhk_wave_inputs.h
test/input_cases/windpower_cases.h
test/ssc_test/csp_common_test.h

Add licenses to the top of files that needed them.
I'll push a list of files that don't need them to SAM-documentation for future reference.

add licenses to files that needed them

---

test/shared_test/lib_geothermal_test.h

-test failure caught in Github Actions
-Closes #685

Added haf initialization to GeothermPlantAnalyzer test setup

---

test/shared_test/lib_geothermal_test.h
test/ssc_test/cmod_battery_pvsamv1_test.cpp

2 minor PRs worth of changes to develop

Patch to develop Dec 9 2021

---

.github/workflows/ci.yml

Working with GitHub actions on Linux. WIP will be removed once this is ready to merge

Github actions on Linux

---

.github/workflows/ci.yml

Add Mac runner to GitHub actions.

GitHub Actions working on Mac build

---

README.md

Update readme file with new GH actions badge and new release number.
Use https://github.com/NREL/ssc/blob/gh-actions-badge/README.md to proofread

Update build badge and release number in citation

---

ssc/cmod_tcsmolten_salt.cpp

Patch could not be automatically merged with develop, so I created this branch to do it

Merge patch mspt cmod

---

shared/lib_shared_inverter.cpp
shared/lib_utility_rate_equations.cpp
shared/lib_utility_rate_equations.h
ssc/cmod_utilityrate5.cpp
test/shared_test/lib_battery_powerflow_test.cpp
test/ssc_test/cmod_utilityrate5_test.cpp

Patch to develop including https://github.com/NREL/ssc/pull/725 and https://github.com/NREL/ssc/pull/723

resolve conflicts in utility rate 5

---

shared/lib_battery_dispatch.cpp
ssc/cmod_pvsamv1.cpp

Patch to develop fix ssc 737

---

ssc/cmod_pvsamv1.cpp
ssc/cmod_pvwattsv8.cpp
test/ssc_test/cmod_pvwattsv8_test.cpp

Added AC capacity factor to pvwattsv8 and updated associated labels in pvsamv1 and pvwattsv8

AC capacity factor

---

shared/lib_windwatts.cpp
test/shared_test/lib_windwatts_test.cpp

Fixes bug for a single turbine using the Wind Resource Probability Distribution option which produced annual energy results that were much, much lower than expected.
fix #724 and add test

Wind Resource PD for Single Turbine

---

ssc/sscapi.cpp

update ssc version from 267 to 268 for patch 1

2021.12.02.r1.ssc.268

---

shared/CMakeLists.txt
ssc/cmod_csp_trough_eqns.cpp
ssc/cmod_financial_eqns.cpp
tcs/CMakeLists.txt

Add splinter as dependency to shared and tcs CMakeLists so that the build order is correct
Add missing return bool to some equations

Minor fixes for PySAM

---

shared/lib_pv_io_manager.cpp

Fix issue where analysis period is undefined in lcoe calculator and no financial model.

Add check for lcoe calculator and no financial model

---

shared/lib_battery_lifetime_calendar_cycle.cpp
shared/lib_pv_io_manager.cpp
ssc/cmod_battery.cpp
ssc/cmod_pvsamv1.cpp
tcs/csp_solver_mono_eq_methods.cpp

Resolve merge conflicts and merge in last few PRs.

Patch to develop 4/11/22

---

shared/lib_pv_io_manager.cpp
ssc/cmod_pvsamv1.cpp

Fixes https://github.com/NREL/SAM/issues/868
For monthly array input, report month and value in error message.
For weather data input, throw error on invalid value and report time step and value in error message.

Improve error handling for albedo

---

ssc/cmod_csp_common_eqns.cpp
ssc/cmod_csp_common_eqns.h
ssc/cmod_csp_tower_eqns.cpp
ssc/cmod_csp_trough_eqns.cpp
ssc/cmod_ui_tes_calcs.cpp
tcs/htf_props.cpp
tcs/htf_props.h

Issue: https://github.com/NREL/SAM/issues/964

Fix UI crash when custom field HTF selected

---

.github/workflows/ci.yml

This needed to go in two places

add the required text to the mac build as well

---

.github/workflows/ci.yml

This needed to be in two places.

Add text to mac build as well in develop

---

shared/lib_util.cpp

Updated with comments and tested with SAM_675 branch of SAM

fixes SAM issue 675 - lib_util::week_of was incorrectly returning 52

---

shared/lib_time.cpp
ssc/cmod_merchantplant_eqns.cpp

cmod_merchant_plant_eqns updated to handle single value inputs
extrapolate_timeseries updated to handle single value array input

Fixes SAM issue 1004

---

ssc/csp_common.cpp

Corrected canting method mapping and setting solarPILOT combo variable.

Fixed bug #1071

---

ssc/cmod_etes_electric_resistance.cpp
ssc/cmod_tcsmolten_salt.cpp
ssc/cmod_trough_physical.cpp
tcs/base_dispatch.cpp
tcs/base_dispatch.h

Reports the number of solves that resulted in suboptimal solution due to hitting iteration limit, time limit, user defined gap, or lpsolve gap.
- Added a output for average mip gap of suboptimal solutions.

adding dispatch report to notices

---

shared/lib_sandia.cpp
test/main.cpp
test/shared_test/lib_battery_dispatch_automatic_btm_test.cpp
test/shared_test/lib_battery_dispatch_automatic_fom_test.cpp
test/ssc_test/cmod_battery_pvsamv1_test.cpp
test/ssc_test/cmod_pvsamv1_test.cpp
test/ssc_test/cmod_pvyield_test.cpp

Already reviewed and approved and all tests passing...

Updates to ssc pull request 842

---

ssc/cmod_pvsamv1_eqns.h

Rebranding of REopt per https://github.com/NREL/SAM/issues/1090

Change "REopt Lite" to "REopt"

---

ssc/cmod_pvwattsv7.cpp
ssc/cmod_pvwattsv8.cpp
test/main.cpp
test/ssc_test/cmod_pvwattsv7_test.cpp
test/ssc_test/cmod_pvwattsv8_test.cpp

DC power loss due to snow (%) output changed from fraction to percentage and tests updated

fix SAM issue 1137

---

ssc/common.cpp

Add additional documentation to the vartable to solve (improve)? #909 
Shouldn't change any code behavior.

add units and metadata for utility rates inputs

---

README.md

update readme with new version number

---

ssc/cmod_pvsamv1.cpp

Fixing poa_rear output and re-implementing annual_poa_rear_gain_percent output.

Fix bifacial gain output

---

ssc/cmod_etes_ptes.cpp
tcs/htf_props.cpp
tcs/htf_props.h

https://github.com/NREL/SAM/issues/1306

Add methanol as cold TES option for PTES

---

ssc/cmod_etes_electric_resistance.cpp

Fixes issue identified in https://github.com/NREL/SAM/issues/1311#event-8154201857

Bug fix SAM Issue 1311

---

tcs/htf_props.cpp
tcs/htf_props.h

1) Fixes issue created when methanol was added in prior patch commit. New fluids must be added to the bottom of the enumeration, because htf codes are hardcoded in the user interface
2) Adds ternary salt HTF to htf properties

Fix and add htf props

---

ssc/cmod_trough_physical.cpp
ssc/cmod_trough_physical_iph.cpp

Enable solar_resource_data in the trough models

---

shared/lib_irradproc.cpp
ssc/cmod_pvsamv1.cpp

Fix rear shading and soiling issue

---

tcs/csp_solver_trough_collector_receiver.cpp

Fix field freeze protection calculation when startup time is zero

---

ssc/cmod_cashloan.cpp
ssc/cmod_communitysolar.cpp
ssc/cmod_equpartflip.cpp
ssc/cmod_fuelcell.cpp
ssc/cmod_host_developer.cpp
ssc/cmod_levpartflip.cpp
ssc/cmod_merchantplant.cpp
ssc/cmod_saleleaseback.cpp
ssc/cmod_singleowner.cpp
test/main.cpp

No longer have random NaNs in financial model outputs for single year technology model runs with analysis periods greater than one

Addresses ssc issue 992

---

shared/lib_battery_voltage.cpp
test/main.cpp
test/ssc_test/cmod_battery_stateful_test.cpp
test/ssc_test/cmod_battery_stateful_test.h

Added battery stateful ssc_1023 test to match with pysam branch 1023 charging-test.py file. Same results on amd64 and arm64.  Issue was in lib_battery_voltage in voltage_table_t::calculate_current_for_target_w

Fixes #1023

---

ssc/sscapi.cpp

2023.9.19.ssc.283 beta release expires 12/19/2023

---

ssc/cmod_hybrid.cpp

Test with develop branches of other repos using SAM test file 
[fuel-cell-replacement-test.zip](https://github.com/NREL/ssc/files/13197762/fuel-cell-replacement-test.zip)
Works for hybrid configurations with user specified replacement schedules
and for percentage fuel cell replacements

Fix fuel cell replacement costs for hybrids - SAM issue 1528

---

ssc/cmod_fuelcell.cpp

Goes with https://github.com/NREL/SAM/pull/1529

add annual energy discharged output for #1056

---

ssc/cmod_fuelcell.cpp
ssc/core.cpp

Adds monthly fuel cell energy discharged output. Adds comments to the accumulate_monthly functions to clarify usage. Closes NREL/SAM#1474.

Add fuel cell monthly energy output

---

.gitattributes

update git attributes file to correctly calculate language breakdown of project with linguist

update git attributes file for linguist

---

ssc/cmod_battery.cpp

Helps with https://github.com/NREL/SAM/issues/1691
Goes with https://github.com/NREL/SAM/pull/1694

Improve batt temp timestep message

---

ssc/sscapi.cpp

2023.12.17.r1.ssc.290 release candidate

---

.gitattributes

Fix lf vs crlf issue as discussed at last week's meeting.

Add json to list of definitely text files

---

test/shared_test/lib_battery_test.cpp
test/ssc_test/cmod_battwatts_test.cpp

Update battery tests for new Mac version on CI

---

ssc/cmod_utilityrate5.cpp
test/ssc_test/cmod_utilityrate5_test.cpp

Solves SAM issue https://github.com/NREL/SAM/issues/1738:
- Correct sell rate during tier changes
- Fix behavior when passing through multiple tiers in one step.
[test/input_cases/utility_rate_data/gen_25_year_residential_w_net_eqns.csv](https://github.com/NREL/ssc/compare/sam_1738_correct_net_billing_sell_rate?expand=1#diff-c779362b56b4e52d39f370768a4704b2158a1e7709d1cd6a8e8a8a523f1d8fe7) contains equations to develop test results

Sam 1738 correct net billing sell rate

---

shared/lib_battery_capacity.cpp
test/shared_test/lib_battery_capacity_test.cpp

Fixes https://github.com/NREL/ssc/issues/1142

Batt Thermal

---

shared/lib_cec6par.cpp

Fixes https://github.com/NREL/SAM/issues/1781
Goes with https://github.com/NREL/SAM/pull/1795

cec6par comment on hard-coded air mass modifier coefficients

---

shared/lib_battery.cpp
shared/lib_battery.h

Add dt_hr options

---

CMakeLists.txt
solarpilot/CMakeLists.txt
ssc/CMakeLists.txt

Goes with following pull requests
lk  https://github.com/NREL/lk/pull/46
wex  https://github.com/NREL/wex/pull/172
ssc  https://github.com/NREL/ssc/pull/1185
SAM  https://github.com/NREL/SAM/pull/1815
SAM-private  https://github.com/NREL/SAM-private/pull/109

Update to minimum MacOS version 12 per SAM #1745

---

ssc/ssc_equations.h

-Issue to address this for next release: https://github.com/NREL/ssc/issues/1197
-Changing this to not have breaking PySAM change for patch.

Remove ssc equations for mhk from pysam for patch

---

ssc/cmod_communitysolar.cpp

Add the debt fraction calcs to community solar. To test:
1. Check out this branch along with (https://github.com/NREL/SAM/pull/1854)
2. Open a default PVWatts-Community Solar case
3. Change to DSCR mode and check the new "Maximum debt fraction" box
4. Run the simulation
5. Debt fraction should be limited to 0%
6. Make the system outrageously profitable by adding revenue
7. Run the simulation again
8. Debt fraction should be <= 100% (or number that you've specified on that page)

Add debt fraction limiting calcs to community solar

---

ssc/cmod_fresnel_physical_iph.cpp
ssc/cmod_trough_physical.cpp
tcs/base_dispatch.cpp
tcs/base_dispatch.h

- problem was cause by NAN values for electricity prices.
- Fresnel physical iph model had the same issue
- added a failed solves count to notice summary

fixing dispatch infeasible problems

---

shared/lib_windfile.cpp

Fix https://github.com/NREL/SAM/issues/1880
Add check for missing data to wind file reader.

Add wind data check for missing data

---

shared/lib_irradproc.cpp
shared/lib_irradproc.h
test/shared_test/lib_irradproc_test.cpp

fix https://github.com/NREL/SAM/issues/1882 by moving the SPA table inside irradproc

Make SPA threadsafe again

---

ssc/cmod_custom_generation.cpp

Deal with merge timing conflicts

Fix haf for custom generation profile

---

shared/lib_windfile.cpp

Addresses https://github.com/NREL/SAM/issues/1990

Address SAM issue 1990 - 5 minute weather data header info

---

ssc/cmod_mhk_tidal.cpp

Details of debugging on MacOS 15.2 in attached Word document.
[GitHubIssuesSAM_2004.docx.zip](https://github.com/user-attachments/files/18732316/GitHubIssuesSAM_2004.docx.zip)

Address SAM issue 2004

---

ssc/cmod_battery.cpp

Fixes https://github.com/NREL/ssc/issues/1301

Fix batt adjust constant typo

---

shared/lib_utility_rate_equations.cpp

Goes with https://github.com/NREL/SAM/pull/2047

Throw error for NaN (or -NaN) or negative max tier usage.

---

ssc/cmod_pvsamv1.cpp
ssc/cmod_pvwattsv8.cpp

Fixes https://github.com/NREL/SAM/issues/2026

Remove bifacial messages for one-axis tracking

---

tcs/csp_solver_packedbed_tes.cpp

Fix boundary condition equations for packed bed TES model. Fix reporting unit bug for packed bed outputs.

Fix minor bugs in packed bed TES model.

---

ssc/sscapi.cpp

2025.4.7.ssc.301 release candidate

---

ssc/cmod_cashloan.cpp

Fixes https://github.com/NREL/sam/issues/2068

Fix cashloan IRR units (% not $)

---

shared/lib_windfile.cpp

Set elevation to zero if not in wind file
Fixes https://github.com/NREL/SAM/issues/2019

Remove wind file elevation check

---

README.md

Change the date and version number on the readme

Readme update for 2025.4.16
